// Additive MySQL/MariaDB schema. Consumption history intentionally outlives trip deletion.
export async function migrateBilling(db){
 const tables=[
 `billing_migrations (name VARCHAR(80) PRIMARY KEY,applied_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3))`,
 `billing_customer_intents (user_id VARCHAR(64) NOT NULL,mode VARCHAR(4) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(user_id,mode),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`,
 `billing_customers (user_id VARCHAR(64) NOT NULL,mode VARCHAR(4) NOT NULL,provider VARCHAR(20) NOT NULL DEFAULT 'stripe',provider_id VARCHAR(100) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(user_id,mode),UNIQUE KEY customer_provider(mode,provider_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`,
 `billing_orders (id VARCHAR(64) PRIMARY KEY,user_id VARCHAR(64) NOT NULL,mode VARCHAR(4) NOT NULL,plan_code VARCHAR(32) NOT NULL,kind VARCHAR(20) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'pending',request_key VARCHAR(100) NOT NULL,price_id VARCHAR(100) NOT NULL,customer_id VARCHAR(100) NULL,checkout_id VARCHAR(100) NULL,payment_id VARCHAR(100) NULL,subscription_id VARCHAR(100) NULL,checkout_url TEXT NULL,amount INT NOT NULL,currency VARCHAR(3) NOT NULL,paid_amount INT NULL,refunded_amount INT NOT NULL DEFAULT 0,refund_credit_removed INT NOT NULL DEFAULT 0,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),paid_at DATETIME(3) NULL,expires_at DATETIME(3) NULL,UNIQUE KEY order_retry(user_id,mode,request_key),UNIQUE KEY checkout_identity(mode,checkout_id),INDEX order_user(user_id,mode,status),INDEX order_payment(mode,payment_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`,
 `billing_subscriptions (provider_id VARCHAR(100) NOT NULL,mode VARCHAR(4) NOT NULL,user_id VARCHAR(64) NOT NULL,plan_code VARCHAR(32) NOT NULL,status VARCHAR(30) NOT NULL,period_start DATETIME(3) NOT NULL,period_end DATETIME(3) NOT NULL,cancel_at_period_end BOOLEAN NOT NULL DEFAULT FALSE,cancel_at DATETIME(3) NULL,delinquent_since DATETIME(3) NULL,last_synced_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(mode,provider_id),INDEX subscription_user(user_id,mode),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`,
 `billing_period_usage (user_id VARCHAR(64) NOT NULL,mode VARCHAR(4) NOT NULL,subscription_id VARCHAR(100) NOT NULL,period_start DATETIME(3) NOT NULL,period_end DATETIME(3) NOT NULL,used INT NOT NULL DEFAULT 0,PRIMARY KEY(mode,subscription_id,period_start),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CHECK(used>=0))`,
 `billing_events (mode VARCHAR(4) NOT NULL,event_id VARCHAR(100) NOT NULL,type VARCHAR(100) NOT NULL,object_id VARCHAR(100) NULL,status VARCHAR(20) NOT NULL DEFAULT 'received',attempts INT NOT NULL DEFAULT 0,error_code VARCHAR(80) NULL,received_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),processed_at DATETIME(3) NULL,PRIMARY KEY(mode,event_id),INDEX event_status(status,received_at))`,
 `billing_credit_lots (id VARCHAR(64) PRIMARY KEY,user_id VARCHAR(64) NOT NULL,mode VARCHAR(4) NOT NULL,order_id VARCHAR(64) NULL,source VARCHAR(30) NOT NULL,granted INT NOT NULL,remaining INT NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),UNIQUE KEY purchase_grant(order_id),INDEX lot_user(user_id,mode,remaining),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CHECK(remaining>=0 AND remaining<=granted))`,
 `billing_credit_ledger (id VARCHAR(64) PRIMARY KEY,user_id VARCHAR(64) NOT NULL,mode VARCHAR(4) NOT NULL,lot_id VARCHAR(64) NULL,order_id VARCHAR(64) NULL,trip_id VARCHAR(64) NULL,delta INT NOT NULL,kind VARCHAR(30) NOT NULL,reason VARCHAR(500) NULL,actor_id VARCHAR(64) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX ledger_user(user_id,mode,created_at),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`,
 `billing_trip_entitlements (trip_id VARCHAR(64) PRIMARY KEY,user_id VARCHAR(64) NOT NULL,source VARCHAR(30) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'active',mode VARCHAR(6) NOT NULL,subscription_id VARCHAR(100) NULL,order_id VARCHAR(64) NULL,lot_id VARCHAR(64) NULL,expires_at DATETIME(3) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX entitlement_user(user_id,mode),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`,
 `billing_free_allowances (user_id VARCHAR(64) PRIMARY KEY,used INT NOT NULL DEFAULT 0,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CHECK(used>=0))`,
 `billing_operations (id VARCHAR(64) PRIMARY KEY,user_id VARCHAR(64) NOT NULL,trip_id VARCHAR(64) NULL,operation VARCHAR(40) NOT NULL,mode VARCHAR(6) NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),INDEX operation_trip(user_id,trip_id,operation,status),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`,
 `billing_upload_scopes (upload_id VARCHAR(64) PRIMARY KEY,trip_id VARCHAR(64) NOT NULL,user_id VARCHAR(64) NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),FOREIGN KEY(upload_id) REFERENCES uploads(id) ON DELETE CASCADE,FOREIGN KEY(trip_id,user_id) REFERENCES trips(id,owner_id) ON DELETE CASCADE,INDEX scope_trip(trip_id,user_id))`,
 ];
 for(const table of tables)await db.query('CREATE TABLE IF NOT EXISTS '+table+' ENGINE=InnoDB');
 await db.query("INSERT IGNORE INTO admin_locks(name)VALUES('billing_initialization')");
 const connection=await db.getConnection();
 try{
  await connection.beginTransaction();await connection.query("SELECT name FROM admin_locks WHERE name='billing_initialization' FOR UPDATE");
  const [[done]]=await connection.query("SELECT name FROM billing_migrations WHERE name='legacy_v1'");
  if(!done){
   await connection.query("INSERT IGNORE INTO billing_trip_entitlements(trip_id,user_id,source,mode)SELECT id,owner_id,'LEGACY_GRANDFATHERED','shared' FROM trips");
   await connection.query('INSERT INTO billing_free_allowances(user_id,used)SELECT owner_id,1 FROM trips GROUP BY owner_id ON DUPLICATE KEY UPDATE used=GREATEST(used,VALUES(used))');
   await connection.query("INSERT INTO billing_migrations(name)VALUES('legacy_v1')");
  }
  await connection.commit();
 }catch(error){await connection.rollback();throw error;}finally{connection.release();}
}
