import {Router} from 'express';
import {rateLimit} from 'express-rate-limit';
import {pool} from '../db.js';
import {requireUser} from '../auth.js';
import {assert} from '../errors.js';
import {billingSettings,publicCatalog} from './configuration.js';
import {getUserBillingState,activateTrip,tripAccess} from './entitlements.js';
import {createCheckout,createPortal,cancelCheckout} from './checkout.js';
import {paymentError} from './stripe.js';
import {billingDiagnosticContext,logBillingError} from './diagnostics.js';
export const billingRouter=Router();
const limited=()=>rateLimit({windowMs:60000,limit:10,keyGenerator:req=>req.user.id,standardHeaders:'draft-8',legacyHeaders:false});
export const safeBilling=fn=>async(req,res,next)=>billingDiagnosticContext.run({stage:'load_config'},async()=>{try{await fn(req,res);}catch(error){logBillingError(error);next(error.status?error:paymentError());}});
billingRouter.get('/plans',safeBilling(async(_req,res)=>res.json(publicCatalog(await billingSettings()))));
billingRouter.use(requireUser);
billingRouter.get('/status',safeBilling(async(req,res)=>res.json(await getUserBillingState(req.user.id))));
billingRouter.get('/trips/:id',safeBilling(async(req,res)=>{const settings=await billingSettings(),access=await tripAccess(pool,req.user.id,req.params.id,settings);const [usage]=await pool.execute("SELECT operation,COUNT(*) AS used FROM billing_operations WHERE user_id=? AND trip_id=? AND status='succeeded' GROUP BY operation",[req.user.id,req.params.id]);res.json({premium:access.premium,source:access.entitlement?.source||'FREE',usage});}));
billingRouter.post('/trips/:id/activate',limited(),safeBilling(async(req,res)=>res.json(await activateTrip(req.user.id,req.params.id))));
billingRouter.post('/checkout',limited(),safeBilling(async(req,res)=>res.json(await createCheckout(req.user,req.body))));
billingRouter.post('/portal',limited(),safeBilling(async(req,res)=>res.json(await createPortal(req.user.id))));
billingRouter.post('/orders/:id/cancel',limited(),safeBilling(async(req,res)=>res.json(await cancelCheckout(req.user.id,req.params.id))));
billingRouter.get('/orders',safeBilling(async(req,res)=>{const settings=await billingSettings();const [items]=await pool.execute('SELECT id,plan_code,status,amount,currency,paid_amount,refunded_amount,created_at,paid_at FROM billing_orders WHERE user_id=? AND mode=? ORDER BY created_at DESC LIMIT 100',[req.user.id,settings.billing_mode]);res.json({items});}));
billingRouter.get('/orders/:id',safeBilling(async(req,res)=>{const settings=await billingSettings();const [[order]]=await pool.execute('SELECT id,plan_code,status,created_at FROM billing_orders WHERE id=? AND user_id=? AND mode=?',[req.params.id,req.user.id,settings.billing_mode]);assert(order,404,'Purchase not found.');res.json(order);}));
