import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api} from '@/api/client';
export default function AccountSecurity(){
 const [sessions,setSessions]=useState(null),[deletion,setDeletion]=useState(null),[action,setAction]=useState(''),[password,setPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=()=>Promise.all([api.account('sessions'),api.account('deletion')]).then(([data,status])=>{setSessions(data.items);setDeletion(status.request);}).catch(e=>setError(e.message));
 useEffect(()=>{load();},[]);
 function open(value){setAction(value);setPassword('');setNewPassword('');setConfirmation('');setError('');}
 async function submit(event){event.preventDefault();setBusy(true);setError('');try{
  const result=await api.account(action==='revoke'?'sessions/revoke':action,{password,newPassword,confirmation:action==='revoke'?'REVOKE':confirmation});
  if(action==='password'){window.location.assign('/login');return;}
  if(action==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='TripSync-my-data.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
  setMessage(result.message|| (action==='revoke'?'Other devices have been signed out.':'Your data export is ready.'));setAction('');setPassword('');await load();
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 const titles={password:'Change password',revoke:'Sign out other devices',deletion:'Request account deletion',export:'Download my data'};
 return <section className="bg-white rounded-xl p-6 sm:p-8 text-neutral-900"><h3 className="font-heading font-bold text-lg">Security & privacy</h3><p className="text-sm text-neutral-600 mt-2">Manage your password, signed-in devices and personal data.</p>{message&&<p role="status" className="mt-4 text-green-800">{message}</p>}{error&&!action&&<p role="alert">{error} <button onClick={load}>Retry</button></p>}<h4 className="font-semibold mt-6">Active sessions</h4>{sessions?<ul className="divide-y divide-neutral-200">{sessions.map(session=><li key={session.id} className="py-3 text-sm"><strong>{session.device_summary||'Browser'}{session.current?' · This device':''}</strong><p>Last active: {session.last_seen_at||session.created_at} UTC</p></li>)}</ul>:<p role="status">Loading sessions…</p>}<div className="grid sm:grid-cols-2 gap-3 mt-6">{Object.entries(titles).map(([key,title])=><button key={key} className="min-h-11 rounded-xl border border-neutral-300 px-4 py-3 text-sm font-medium hover:bg-neutral-100 focus-visible:ring-2 focus-visible:ring-blue-600" onClick={()=>open(key)} disabled={key==='deletion'&&deletion?.status==='PENDING'}>{title}</button>)}</div>{deletion?.status==='PENDING'&&<p className="text-sm mt-4">Your deletion request is pending review. Contact support to cancel it.</p>}
 <Dialog open={!!action} onOpenChange={value=>{if(!value&&!busy){setAction('');setPassword('');}}}><DialogContent className="bg-neutral-950 text-white border-white/15"><DialogTitle>{titles[action]}</DialogTitle><DialogDescription>{action==='deletion'?'This requests permanent removal of your account, trips and private files after review. Download your data first. Nothing is deleted immediately.':action==='export'?'Downloads your profile and saved records as JSON. Private file contents and security credentials are excluded.':action==='password'?'Your new password signs out all devices, including this one.':'Your current device stays signed in. Other devices will need to sign in again.'}</DialogDescription><form onSubmit={submit} className="space-y-4"><label className="block text-sm">Current password<input className="mt-2 w-full rounded-lg bg-white/10 p-3" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{action==='password'&&<label className="block text-sm">New password (12–128 characters)<input className="mt-2 w-full rounded-lg bg-white/10 p-3" type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label>}{action==='deletion'&&<label className="block text-sm">Type DELETE MY ACCOUNT<input className="mt-2 w-full rounded-lg bg-white/10 p-3" required value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>}{error&&<p role="alert" className="text-amber-200">{error}</p>}<div className="flex gap-3"><button className="min-h-11 px-4 rounded-lg bg-lime text-black" disabled={busy||(action==='deletion'&&confirmation!=='DELETE MY ACCOUNT')}>{busy?'Please wait…':'Confirm'}</button><button type="button" className="min-h-11 px-4 rounded-lg bg-white/10" disabled={busy} onClick={()=>{setAction('');setPassword('');}}>Cancel</button></div></form></DialogContent></Dialog>
 </section>;
}
