import { t, translateText } from "@/i18n/runtime";
import { useLocale } from "@/i18n/react";
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api} from '@/api/client';
export default function AccountSecurity(){
  useLocale();
 const [sessions,setSessions]=useState(null),[deletion,setDeletion]=useState(null),[action,setAction]=useState(''),[password,setPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=()=>Promise.all([api.account('sessions'),api.account('deletion')]).then(([data,status])=>{setSessions(data.items);setDeletion(status.request);}).catch(e=>setError(e.message));
 useEffect(()=>{load();},[]);
 function open(value){setAction(value);setPassword('');setNewPassword('');setConfirmation('');setError('');}
 async function submit(event){event.preventDefault();setBusy(true);setError('');try{
  const result=await api.account(action==='revoke'?'sessions/revoke':action,{password,newPassword,confirmation:action==='revoke'?'REVOKE':confirmation});
  if(action==='password'){window.location.assign('/login');return;}
  if(action==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='TripNexa-my-data.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
  setMessage(result.message|| (action==='revoke'?'Other devices have been signed out.':'Your data export is ready.'));setAction('');setPassword('');await load();
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 const titles={password:'Change password',revoke:'Sign out other devices',deletion:'Request account deletion',export:'Download my data'};
 return <section className="bg-white rounded-xl p-6 sm:p-8 text-neutral-900"><h3 className="font-heading font-bold text-lg">{t("ui.security.privacy.956f817")}</h3><p className="text-sm text-neutral-600 mt-2">{t("ui.manage.your.password.signed.in.devices.and.personal.data.c2795a9")}</p>{message&&<p role="status" className="mt-4 text-green-800">{translateText(message)}</p>}{error&&!action&&<p role="alert">{translateText(error)} <button onClick={load}>{t("ui.retry.942087c")}</button></p>}<h4 className="font-semibold mt-6">{t("ui.active.sessions.61ad990")}</h4>{sessions?<ul className="divide-y divide-neutral-200">{sessions.map(session=><li key={session.id} className="py-3 text-sm"><strong>{session.device_summary||t("ui.browser.d31de1a")}{session.current?t("ui.this.device.7fe92f1"):''}</strong><p>{t("ui.last.active.1cf581d")}{" "}{session.last_seen_at||session.created_at}{" "}{t("ui.utc.7e5f76c")}</p></li>)}</ul>:<p role="status">{t("ui.loading.sessions.c4141f5")}</p>}<div className="grid sm:grid-cols-2 gap-3 mt-6">{Object.entries(titles).map(([key,title])=><button key={key} className="min-h-11 rounded-xl border border-neutral-300 px-4 py-3 text-sm font-medium hover:bg-neutral-100 focus-visible:ring-2 focus-visible:ring-blue-600" onClick={()=>open(key)} disabled={key==='deletion'&&deletion?.status==='PENDING'}>{translateText(title)}</button>)}</div>{deletion?.status==='PENDING'&&<p className="text-sm mt-4">{t("ui.your.deletion.request.is.pending.review.contact.support.to.cancel.cfa4024")}</p>}
 <Dialog open={!!action} onOpenChange={value=>{if(!value&&!busy){setAction('');setPassword('');}}}><DialogContent className="bg-neutral-950 text-white border-white/15"><DialogTitle>{translateText(titles[action])}</DialogTitle><DialogDescription>{action==='deletion'?t("ui.this.requests.permanent.removal.of.your.account.trips.and.private.bf5c1de"):action==='export'?t("ui.downloads.your.profile.and.saved.records.as.json.private.file.con.c8ba3e1"):action==='password'?t("ui.your.new.password.signs.out.all.devices.including.this.one.d2a9721"):t("ui.your.current.device.stays.signed.in.other.devices.will.need.to.si.758edaa")}</DialogDescription><form onSubmit={submit} className="space-y-4"><label className="block text-sm">{t("ui.current.password.72ed2bd")}<input className="mt-2 w-full rounded-lg bg-white/10 p-3" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{action==='password'&&<label className="block text-sm">{t("ui.new.password.12.128.characters.864d22f")}<input className="mt-2 w-full rounded-lg bg-white/10 p-3" type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label>}{action==='deletion'&&<label className="block text-sm">{t("ui.type.delete.my.account.4cef8e7")}<input className="mt-2 w-full rounded-lg bg-white/10 p-3" required value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>}{error&&<p role="alert" className="text-amber-200">{translateText(error)}</p>}<div className="flex gap-3"><button className="min-h-11 px-4 rounded-lg bg-lime text-black" disabled={busy||(action==='deletion'&&confirmation!=='DELETE MY ACCOUNT')}>{busy?t("ui.please.wait.4660a98"):t("ui.confirm.eebdd24")}</button><button type="button" className="min-h-11 px-4 rounded-lg bg-white/10" disabled={busy} onClick={()=>{setAction('');setPassword('');}}>{t("ui.cancel.19766ed")}</button></div></form></DialogContent></Dialog>
 </section>;
}
