import {useEffect,useState} from 'react';
import {socialApi} from '@/api/social';
import SocialButtons from '@/components/SocialButtons';
export default function ConnectedAccounts(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[password,setPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=()=>socialApi('/account/identities').then(setData).catch(e=>setError(e.message));useEffect(()=>{load();},[]);
 async function run(path,body){setBusy(true);setError('');try{await socialApi(path,body);setPassword('');setNewPassword('');setMessage('Your sign-in methods have been updated.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="bg-white text-neutral-900 rounded-xl p-6 sm:p-8"><h3 className="font-bold text-lg">Connected accounts</h3><p className="text-sm text-neutral-600 mt-2">Manage Google, Apple and password sign-in. Keep at least one available method.</p>{error&&<p role="alert" className="my-3 text-red-700">{error}</p>}{message&&<p role="status" className="my-3 text-green-800">{message}</p>}{!data?<p role="status">Loading sign-in methods…</p>:<><p className="my-4">Password: {data.has_password?'Configured':'Not configured'}</p>{data.has_password&&<label className="block text-sm">Current password (if recent verification expired)<input className="block w-full border rounded-lg p-3 mt-2" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>}<ul>{data.identities.map(i=><li key={i.provider} className="flex flex-wrap items-center justify-between gap-3 py-4 border-b"><span><strong className="capitalize">{i.provider}</strong><span className="block text-sm">{i.provider_email||'Connected'}</span></span><button disabled={busy} onClick={()=>run('/account/identities/'+i.provider+'/disconnect',{password})} className="border rounded-lg p-3">Disconnect</button></li>)}</ul><SocialButtons intent="connect" returnTo="/profile" password={password} only={['google','apple'].filter(p=>!data.identities.some(i=>i.provider===p))}/>{!data.recent_auth&&<SocialButtons intent="reauth" returnTo="/profile" only={data.identities.map(i=>i.provider)}/>} {!data.has_password&&<form className="mt-5 space-y-3" onSubmit={e=>{e.preventDefault();run('/account/password/create',{newPassword});}}><label className="block">Add a password<input type="password" className="block w-full border rounded-lg p-3 mt-2" autoComplete="new-password" minLength={12} maxLength={128} required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><p className="text-sm">Use 12–128 characters. Recent sign-in is required. A password also enables data export and account deletion confirmation.</p><button disabled={busy} className="border rounded-lg p-3">Create password</button></form>}</>}</section>;
}
