import { t, translateText } from "@/i18n/runtime";
import { useLocale } from "@/i18n/react";
import {useEffect,useState} from 'react';
import {socialApi} from '@/api/social';
import SocialButtons from '@/components/SocialButtons';
export default function ConnectedAccounts(){
  useLocale();
 const [data,setData]=useState(null),[error,setError]=useState(''),[password,setPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=()=>socialApi('/account/identities').then(setData).catch(e=>setError(e.message));useEffect(()=>{load();},[]);
 async function run(path,body){setBusy(true);setError('');try{await socialApi(path,body);setPassword('');setNewPassword('');setMessage('Your sign-in methods have been updated.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="bg-white text-neutral-900 rounded-xl p-6 sm:p-8"><h3 className="font-bold text-lg">{t("ui.connected.accounts.2fc385c")}</h3><p className="text-sm text-neutral-600 mt-2">{t("ui.manage.google.apple.and.password.sign.in.keep.at.least.one.availa.de4ced6")}</p>{error&&<p role="alert" className="my-3 text-red-700">{translateText(error)}</p>}{message&&<p role="status" className="my-3 text-green-800">{translateText(message)}</p>}{!data?<p role="status">{t("ui.loading.sign.in.methods.5634ff4")}</p>:<><p className="my-4">{t("ui.password.569b248")}{" "}{data.has_password?t("ui.configured.84aebc6"):t("ui.not.configured.dd1841d")}</p>{data.has_password&&<label className="block text-sm">{t("ui.current.password.if.recent.verification.expired.35e1f0a")}<input className="block w-full border rounded-lg p-3 mt-2" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>}<ul>{data.identities.map(i=><li key={i.provider} className="flex flex-wrap items-center justify-between gap-3 py-4 border-b"><span><strong className="capitalize">{i.provider}</strong><span className="block text-sm">{i.provider_email||t("ui.connected.2296556")}</span></span><button disabled={busy} onClick={()=>run('/account/identities/'+i.provider+'/disconnect',{password})} className="border rounded-lg p-3">{t("ui.disconnect.acfc5be")}</button></li>)}</ul><SocialButtons intent="connect" returnTo="/profile" password={password} only={['google','apple'].filter(p=>!data.identities.some(i=>i.provider===p))}/>{!data.recent_auth&&<SocialButtons intent="reauth" returnTo="/profile" only={data.identities.map(i=>i.provider)}/>} {!data.has_password&&<form className="mt-5 space-y-3" onSubmit={e=>{e.preventDefault();run('/account/password/create',{newPassword});}}><label className="block">{t("ui.add.a.password.a4e0337")}<input type="password" className="block w-full border rounded-lg p-3 mt-2" autoComplete="new-password" minLength={12} maxLength={128} required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><p className="text-sm">{t("ui.use.12.128.characters.recent.sign.in.is.required.a.password.also.642bc88")}</p><button disabled={busy} className="border rounded-lg p-3">{t("ui.create.password.fa1ac11")}</button></form>}</>}</section>;
}
