import {storageAdminRouter} from '../storage/admin.js';
import { Router } from 'express';
import {affiliateAdminRouter} from '../affiliate-providers/admin.js';
import {authenticationAdminRouter} from '../social-auth/admin.js';
import {billingAdminRouter} from '../billing/admin.js';
import { requireAdmin } from './permissions.js';
import { usersRouter } from './users.js';
import { operationsRouter } from './operations.js';
import { tripsAdminRouter } from './trips.js';
import { settingsRouter } from './settings.js';
import { providersRouter } from './providers.js';
import { brandingRouter } from './branding.js';
import { filesRouter } from './storage.js';
import {publicItineraryAdmin} from '../public-itineraries/admin.js';
export const adminRouter=Router();
adminRouter.use(requireAdmin);
adminRouter.use('/public-itineraries',publicItineraryAdmin);
adminRouter.use(storageAdminRouter);
adminRouter.use('/billing',billingAdminRouter);
adminRouter.use(authenticationAdminRouter);
adminRouter.use('/affiliates',affiliateAdminRouter);
adminRouter.get('/session',(req,res)=>res.json({id:req.user.id,name:req.user.display_name||'',email:req.user.email,role:req.user.role,status:req.user.status}));
adminRouter.use('/users',usersRouter);
adminRouter.use('/trips',tripsAdminRouter);
adminRouter.use(operationsRouter);
adminRouter.use(brandingRouter);
adminRouter.use(settingsRouter);
adminRouter.use(providersRouter);
adminRouter.use(filesRouter);
adminRouter.use((_req,res)=>res.status(404).json({error:'Administrator endpoint not found.'}));
