import {pdfLabel,pdfText,pdfDate,pdfFontCss,serverLocale,withPdfTranslations} from '../pdf-i18n.js';
import {escapeHtml as e,renderPdf} from '../itinerary-pdf.js';
import {countryName} from '../../src/lib/country-codes.js';
import {essentialsPdfAbout,visibleEssentialsSections,verifiedTravelNotices,incompleteEssentialsMessage} from '../../src/lib/essentials-guidance.js';
import {validFact} from './essentials-policy.js';
import {evaluateCompleteness} from './essentials-generation.js';
export function printableEssentials(snapshot){
 const countries=(snapshot.countries||[]).map(country=>({...country,sections:(country.sections||[]).map(section=>({...section,facts:(section.facts||[]).map(fact=>validFact(fact,section.key,country.code)).filter(Boolean)}))}));
 return evaluateCompleteness({...snapshot,countries},{current:snapshot.generation?.current===true});
}
export const essentialsCompletenessHtml=snapshot=>snapshot.generation?.status!=='complete'||!snapshot.generation?.current?`<p class="notice">${e(pdfLabel(incompleteEssentialsMessage))} ${e(pdfLabel("Update information in TripNexa to prepare a new brief."))}</p>`:'';
export function essentialsPdfHtml(trip,snapshot){
 snapshot=printableEssentials(snapshot);const countries=snapshot.countries,passport=snapshot.travelerPassportCountry?countryName(snapshot.travelerPassportCountry,serverLocale()):pdfLabel("Not selected");
 const factHtml=fact=>`<li>${e(pdfText(fact.text))}${fact.sourceType==='official'&&fact.verifiedAt?`<span class="verified">✓ ${e(pdfLabel("Verified"))}</span><a class="source" href="${e(fact.sourceUrl)}">${e(pdfLabel("Official source"))} ↗ · ${e(fact.sourceUrl)}</a>`:''}</li>`;
 return `<!doctype html><html lang="${serverLocale()}"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; font-src data:"><title>TripNexa · ${e(pdfLabel("Before You Go"))}</title><style>${pdfFontCss}
 @page{size:A4;margin:15mm 15mm 18mm}*{box-sizing:border-box}body{font:10pt/1.5 Arial,'Yu Gothic',sans-serif;color:#292c2b;margin:0;background:white}.brand{display:flex;align-items:center;gap:8px;font-size:20pt;font-weight:bold}.brand svg{width:32px;height:32px}.eyebrow{color:#854531;font-size:9pt;font-weight:bold;letter-spacing:2px;margin:20px 0 5px}h1{font:700 29pt/1.2 Georgia,serif;margin:6px 0}h2{font:700 20pt/1.3 Georgia,serif;margin:25px 0 12px;break-after:avoid}h3{font-size:11pt;margin:0 0 7px;color:#854531}p{margin:4px 0}.meta{padding:14px;background:#fff3ec;border:1px solid #ead5c9;border-radius:12px;margin:18px 0}.sections{display:grid;grid-template-columns:minmax(0,1fr);gap:12px;align-items:start}.card{padding:13px;border:1px solid #dedfd7;border-radius:10px;break-inside:avoid;background:#faf9f6}.card ul{padding-left:15px;margin:0}.card li{margin-bottom:8px;overflow-wrap:anywhere}.verified{display:block;color:#3d644b;font-size:8pt;margin-top:4px}.source{font-size:8pt;color:#315e7e;display:block;overflow-wrap:anywhere}.notice{padding:12px;border:1px solid #dfb8a8;background:#fff3ec;border-radius:10px;margin-bottom:14px;break-inside:avoid}.sources{font-size:8pt;margin-top:18px}.sources ul{display:grid;grid-template-columns:1fr 1fr;gap:6px 15px;padding-left:15px}.sources li{break-inside:avoid}.about{margin-top:20px;padding:14px;border-top:3px solid #ffc7b0;break-inside:avoid;font-size:9pt;color:#646963}.updated{font-size:8pt;color:#646963;margin-top:10px}a{color:#315e7e}header,section{overflow-wrap:anywhere}
 </style></head><body><header><div class="brand"><svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><rect width="24" height="24" rx="7" fill="#ffc7b0"/><circle cx="12" cy="12" r="7" fill="none" stroke="#292c2b"/><path d="M16 8l-2 6-6 2 2-6z" fill="none" stroke="#292c2b"/></svg>TripNexa</div><p class="eyebrow">${e(pdfLabel("Before You Go"))}</p><h1>${e(countries.map(country=>country.country).join(' · ')||trip.country||pdfLabel("Destination essentials"))}</h1><p>${e(trip.destination_city||trip.destination||'')} · ${e(pdfDate(trip.start_date))} – ${e(pdfDate(trip.end_date))}</p><div class="meta"><strong>${e(pdfLabel("Passport:"))}</strong> ${e(passport)}<br>${e(pdfLabel("Practical guidance for your saved trip."))}</div></header>
 ${essentialsCompletenessHtml(snapshot)}${countries.map(country=>`<section>${countries.length>1?`<h2>${e(country.country)}</h2>`:''}${verifiedTravelNotices(country).map(fact=>`<aside class="notice"><h3>${e(pdfLabel("Important travel notice"))}</h3><ul>${factHtml(fact)}</ul><p class="updated">${e(pdfLabel("Checked:"))} ${e(pdfDate(fact.verifiedAt))}</p></aside>`).join('')}<div class="sections">${visibleEssentialsSections(country).map(section=>`<article class="card"><h3>${e(pdfLabel(section.title))}</h3><ul>${section.facts.map(factHtml).join('')}</ul>${['entryDocuments','emergency'].includes(section.key)&&!section.facts.some(fact=>fact.verifiedAt)&&country.authorities?.[section.key==='entryDocuments'?'entry':'emergency']?`<a class="source" href="${e(country.authorities[section.key==='entryDocuments'?'entry':'emergency'])}">${e(pdfLabel("Check official"))} ${section.key==='entryDocuments'?pdfLabel("entry guidance"):pdfLabel("emergency authority")}</a>`:''}</article>`).join('')}</div><aside class="sources"><h3>${e(pdfLabel("Official authorities & sources"))}</h3><ul>${[...new Set([...(country.sources||[]),...country.sections.flatMap(section=>section.facts.filter(fact=>fact.verifiedAt).map(fact=>fact.sourceUrl))])].map(url=>`<li><a href="${e(url)}">${e(url)}</a></li>`).join('')}</ul></aside></section>`).join('')}
 <aside class="about"><p class="eyebrow">${e(pdfLabel("About this information"))}</p><p>${e(pdfLabel(essentialsPdfAbout))}</p><p class="updated">${e(pdfLabel("Last updated:"))} ${e(snapshot.generatedAt?pdfDate(snapshot.generatedAt)+' UTC':pdfLabel("Not updated yet"))}</p></aside></body></html>`;
}
export const renderEssentialsPdf=(trip,snapshot)=>withPdfTranslations(snapshot,trip.owner_id||trip.created_by_id,()=>renderPdf(essentialsPdfHtml(trip,snapshot)));
