import {pdfLabel,pdfText,pdfDate,pdfNumber,pdfCount,pdfFontCss,serverLocale,withPdfTranslations} from '../pdf-i18n.js';
import QRCode from 'qrcode';
import {escapeHtml as e,renderPdf} from '../itinerary-pdf.js';
import {mealChoice} from '../../src/lib/dining.js';
import {itineraryTimeLabel} from '../../src/lib/itinerary-time-label.js';
import {buildTripMap} from '../../src/lib/interactive-trip-map.js';
import {buildMapsLink} from '../../src/lib/planningEngine.js';
import {relatedWalletItems} from '../../src/lib/wallet-links.js';

import {weatherKindLabel,temperatureLabel} from '../../src/lib/trip-weather.js';
import {trustedSource} from './essentials-sources.js';
import {visibleEssentialsSections,verifiedTravelNotices,essentialsPdfAbout} from '../../src/lib/essentials-guidance.js';
import {countryName} from '../../src/lib/country-codes.js';
import {printableEssentials,essentialsCompletenessHtml} from './essentials-pdf.js';
import {renderDayMap,pdfDayWithAccommodation} from './pdf-day-map.js';
export {schematicDayMap} from './pdf-day-map.js';

export function safeBookLink(value){try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)&&!url.username&&!url.password?url.href:null;}catch{return null;}}
export function printablePublicLink(value){const safe=safeBookLink(value);if(!safe)return null;const url=new URL(safe);return url.protocol==='https:'&&!/^(localhost|127\.|\[::1\])/.test(url.hostname)&&!url.hostname.endsWith('.local')&&!url.hostname.endsWith('.test')?safe:null;}
export async function travelBookHtml(state,plan,wallet,{applicationUrl,essentials=null,weather=[],basemapProvider=null}={}){
 const trip=state.trip,days=buildTripMap({trip,items:plan.items,dates:plan.dates,stays:state.tripItems,selections:state.places}).map(day=>pdfDayWithAccommodation(day,state.tripItems)),base=applicationUrl?new URL(`/trip/${encodeURIComponent(trip.id)}`,applicationUrl).href:null;
 const link=(url,text)=>safeBookLink(url)?`<a href="${e(safeBookLink(url))}">${e(text)}</a>`:e(text);
 const walletLink=item=>base?`${base}/wallet?item=${encodeURIComponent(item.id)}`:null;
 const qr=async url=>printablePublicLink(url)?(await QRCode.toString(url,{type:'svg',margin:4,errorCorrectionLevel:'M'})).replace('<svg ','<svg class="qr" role="img" aria-label="Open live route QR" shape-rendering="crispEdges" '):'';
 // Fetch maps one day at a time so a long book cannot burst past provider limits.
 const pages=[];for(const [index,day] of days.entries()){
  const daily=plan.items.filter(item=>item.date===day.date),route=daily.find(item=>['transport','transfer'].includes(item.step_type)&&buildMapsLink({origin:item.route_origin,destination:item.route_destination,mode:item.route_mode})),routeUrl=route?buildMapsLink({origin:route.route_origin,destination:route.route_destination,mode:route.route_mode}):null;
  const climate=weather.find(value=>value.date===day.date&&value.temperature);
  pages.push(`<section class="day page"><header class="day-heading"><div><p class="eyebrow">${e(pdfLabel("Day"))} ${index+1}</p><h2>${e(pdfDate(day.date))}</h2></div>${climate?`<p class="weather">${e(temperatureLabel(climate.temperature.highC,'C'))} / ${e(temperatureLabel(climate.temperature.lowC,'C'))}C · ${e(pdfLabel(weatherKindLabel(climate)))}<br><span class="fine">${e(climate.locationLabel)} · ${climate.kind==='forecast'?'MET Norway (CC BY 4.0)':'NASA POWER monthly climatology'}</span></p>`:''}</header>
   <div class="map-box"><p class="eyebrow">${e(pdfLabel("Day Map · saved stops"))}</p>${await renderDayMap(day,basemapProvider)}${routeUrl?`<div class="live-route">${await qr(routeUrl)}<p>${link(routeUrl,pdfLabel("Open live route"))}<br><span class="fine">${e(pdfLabel("Check current directions and travel times."))}</span></p></div>`:''}</div>
   <div class="timeline">${daily.map(item=>{
    const restaurant=mealChoice(item),tickets=relatedWalletItems(item,wallet,state.places),booking=(state.bookings||[]).find(value=>value.selection_id===item.selection_id);
    const isTransfer=['transport','transfer'].includes(item.step_type),url=isTransfer?buildMapsLink({origin:item.route_origin,destination:item.route_destination,mode:item.route_mode}):null;
    const mark=day.stops.find(stop=>stop.itemId===item.id&&stop.kind!=='endpoint');
    const status=tickets.length?pdfLabel("Reservation / ticket in Wallet"):item.ticket_status==='free'?pdfLabel("Free"):item.ticket_status==='purchased'?pdfLabel("Booking confirmed"):booking?.declared_booked?pdfLabel("Marked booked by traveler"):item.step_type==='visit'?pdfLabel("Check ticket requirements"):'';
    return `<article class="entry ${isTransfer?'transfer':''} ${['access','buffer','free','free_time','break','rest'].includes(item.step_type)?'minor':''}"><div class="time">${e(pdfLabel(itineraryTimeLabel(item)))}</div><div class="entry-content"><h3>${mark?`<span class="number">${mark.kind==='stay'?'H':mark.number}</span> `:''}${e(restaurant?pdfLabel('Meal')+' · '+restaurant.name:pdfText(item.title))}</h3>${(restaurant?.address||item.address||item.location)?`<p class="muted">${e(restaurant?.address||item.address||item.location)}</p>`:''}${isTransfer?`<p>${e(pdfLabel(item.route_mode||'Transfer'))} · ${e(pdfNumber(item.route_duration_min??item.duration_min??'Unknown'))} min ${e(pdfLabel("(estimate)"))}</p><p class="muted">${e(item.route_origin||'')} → ${e(item.route_destination||'')}</p>${url?link(url,pdfLabel("Open live route")):''}`:''}${status?`<p class="ticket">${e(status)}${booking?.provider?` · ${e(booking.provider)}`:''}${tickets.length?` · ${link(walletLink(tickets[0]),pdfLabel("Open saved ticket"))}`:''}</p>`:''}</div></article>`;
   }).join('')||`<p class="muted">${e(pdfLabel('No saved activities for this day.'))}</p>`}</div></section>`);
 }
 if(essentials)essentials=printableEssentials(essentials);
 const verified=essentials?.countries||[];
 return `<!doctype html><html lang="${serverLocale()}"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; font-src data:; img-src data:"><title>${e(trip.name)} · ${e(pdfLabel("Full Travel Book"))}</title><style>${pdfFontCss}
 @page{size:A4;margin:15mm 15mm 18mm}*{box-sizing:border-box}body{margin:0;font:10pt/1.4 Arial,sans-serif;color:#292c2b;background:white}h1{font:700 34pt/1.1 Georgia,serif;margin:20px 0}h2{font:700 20pt/1.2 Georgia,serif;margin:5px 0}h3{font-size:10pt;margin:0}p{margin:3px 0}.brand{display:flex;align-items:center;gap:8px;font-weight:700;font-size:18pt}.brand svg{width:30px;height:30px}.eyebrow{font-size:8pt;text-transform:uppercase;letter-spacing:1.5px;font-weight:bold;color:#854531}.muted{color:#646963}.fine{font-size:8pt;color:#646963}.cover{padding:22mm 0 12mm}.cover-summary{background:#fff4ee;border:1px solid #ead5c9;border-radius:10px;padding:18px;margin:25px 0}.cover-grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.page{break-before:page}.day-heading{display:flex;justify-content:space-between;gap:12px;border-bottom:3px solid #ffc7b0;padding-bottom:10px;margin-bottom:12px;break-after:avoid}.map-box{border:1px solid #dedfd7;border-radius:10px;background:#faf9f6;padding:10px;margin-bottom:12px;break-inside:avoid}.day-map{display:block;width:100%;height:auto;aspect-ratio:600/220}.map-legend{font-size:8pt}.live-route{display:flex;align-items:center;gap:10px;margin-top:8px;break-inside:avoid;page-break-inside:avoid}.qr{display:block;width:76px;height:76px;flex-shrink:0}.entry{display:flex;gap:12px;padding:7px 9px;border-bottom:1px solid #e6e4df;break-inside:avoid}.entry-content{min-width:0;overflow-wrap:anywhere}.time{width:80px;flex-shrink:0;font-size:9pt;font-variant-numeric:tabular-nums}.number{display:inline-block;min-width:16px;text-align:center;background:#ffc7b0;border-radius:4px}.transfer{background:#f4f7f9;font-size:9pt}.minor{font-size:9pt;color:#646963;padding:5px 9px}.minor h3{font-weight:normal;font-size:9pt}.ticket{font-size:8pt;color:#3d644b}a{color:#315e7e;text-decoration:underline;overflow-wrap:anywhere}.wallet-grid,.essentials-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:15px}.wallet-card,.essentials-card{border:1px solid #dedfd7;border-radius:8px;padding:12px;break-inside:avoid}.essentials-card h3{color:#854531;margin-bottom:6px}.essentials-country{margin-bottom:16px}.essentials-country>h2{break-after:avoid}.essentials-card ul{padding-left:15px;margin:0}.source{font-size:7.5pt;margin-top:6px}.weather{font-size:9pt;text-align:right;max-width:230px}.footer-note{margin-top:18px;padding:12px;background:#faf9f6;border-radius:8px;font-size:8pt}section,header{overflow-wrap:anywhere}
 </style></head><body><section class="cover"><div class="brand"><svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-label="TripNexa compass"><rect width="24" height="24" rx="7" fill="#ffc7b0"/><circle cx="12" cy="12" r="7" fill="none" stroke="#292c2b"/><path d="M16 8l-2 6-6 2 2-6z" fill="none" stroke="#292c2b"/></svg>TripNexa.</div><p class="eyebrow" style="margin-top:25px">${e(pdfLabel("Your personal Full Travel Book"))}</p><h1>${e(trip.destination_city||trip.destination||trip.name)}</h1><p>${e(trip.name)}</p><p class="muted">${e(pdfDate(trip.start_date))} – ${e(pdfDate(trip.end_date))} · ${e(pdfCount("days",days.length))} · ${e(trip.timezone||pdfLabel("Timezone not set"))}</p><div class="cover-summary cover-grid"><div><p class="eyebrow">${e(pdfLabel("Travelers"))}</p><p>${e(pdfCount("adults",trip.adults||1))}${trip.children_ages?` · ${e(pdfCount("children",String(trip.children_ages).split(',').filter(Boolean).length))}`:''}</p></div><div><p class="eyebrow">${e(pdfLabel("Accommodation"))}</p>${state.tripItems.filter(item=>item.category==='stay').map(stay=>`<p>${e(stay.title||pdfLabel("Stay"))}<br><span class="fine">${e(stay.address||pdfLabel("Address to confirm"))}</span></p>`).join('')||`<p>${e(pdfLabel('No saved stay'))}</p>`}</div></div><p class="muted">${e(pdfLabel("Your saved schedule, numbered day maps, live routes and booking summaries in one place."))}</p>${base?`<p>${link(base+'/itinerary',pdfLabel("Open your private trip"))} · ${link(base+'/wallet',pdfLabel("Open Travel Wallet"))}</p>`:''}<div class="footer-note">${e(pdfLabel("This book reflects the currently saved itinerary. It does not update automatically. Routes and times are estimates. Original ticket documents, private notes, passport details and booking credentials are not embedded. App and Wallet links require sign-in."))}</div></section>
 ${pages.join('')}
 ${wallet.length?`<section class="page"><p class="eyebrow">${e(pdfLabel("Travel Wallet"))}</p><h2>${e(pdfLabel("Bookings & documents"))}</h2><p class="muted">${e(pdfLabel("Original files remain securely in your Travel Wallet."))}</p><div class="wallet-grid">${wallet.map(item=>`<article class="wallet-card"><p class="eyebrow">${e(pdfLabel(item.category))}</p><h3>${e(item.title||item.category)}</h3><p>${e(pdfDate(item.date||item.departure_datetime?.slice(0,10)))}${item.time?` · ${e(item.time)}`:''}</p>${item.category==='stay'?`<p class="muted">${e(item.address||'')}</p>`:''}<p class="fine">${e(pdfLabel(item.booking_status||'Status to confirm'))} · ${item.attachments?.length||0} ${e(pdfLabel("saved file(s)"))}</p>${walletLink(item)?link(walletLink(item),pdfLabel("Open in Travel Wallet")):''}</article>`).join('')}</div></section>`:''}
 <section class="page"><p class="eyebrow">${e(pdfLabel("Destination essentials"))}</p><h2>${e(pdfLabel("Before You Go"))}</h2>${essentials?essentialsCompletenessHtml(essentials):''}${verified.length?verified.map(country=>`<div class="essentials-country"><h2>${e(country.country)}</h2><p class="fine">${e(pdfLabel("Passport:"))} ${e(essentials.travelerPassportCountry?countryName(essentials.travelerPassportCountry,serverLocale()):pdfLabel("Not selected"))} · ${e(pdfLabel("Last updated:"))} ${e(essentials.generatedAt?pdfDate(essentials.generatedAt):pdfLabel("Not updated yet"))}<br>${e(pdfLabel("Last checked:"))} ${e(country.checkedAt?pdfDate(country.checkedAt):pdfLabel("Not checked"))}${essentials.stale?` · ${e(pdfLabel('Refresh recommended'))}`:''}</p>${verifiedTravelNotices(country).map(fact=>`<aside class="footer-note"><h3>${e(pdfLabel("Important travel notice"))}</h3><p>${e(pdfText(fact.text))}</p><p class="fine">${e(pdfLabel("Verified"))} · ${e(pdfLabel("Checked:"))} ${e(pdfDate(fact.verifiedAt))}</p>${link(fact.sourceUrl,pdfLabel("Official source"))}</aside>`).join('')}<div class="essentials-grid">${visibleEssentialsSections(country).map(section=>`<article class="essentials-card"><h3>${e(pdfLabel(section.title))}</h3><ul>${section.facts.map(fact=>`<li>${e(pdfText(fact.text))}${fact.sourceType==='official'&&fact.verifiedAt&&trustedSource(fact.sourceUrl,country.code)?`<div class="source"><span>✓ ${e(pdfLabel("Verified"))}</span><br>${link(fact.sourceUrl,pdfLabel("Official source"))}</div>`:''}</li>`).join('')}</ul>${['entryDocuments','emergency'].includes(section.key)&&!section.facts.some(fact=>fact.verifiedAt)&&country.authorities?.[section.key==='entryDocuments'?'entry':'emergency']?link(country.authorities[section.key==='entryDocuments'?'entry':'emergency'],pdfLabel("Check official authority")):''}</article>`).join('')}</div><div class="source"><h3>${e(pdfLabel("Official authorities & sources"))}</h3>${(country.sources||[]).map(url=>link(url,url)).join('<br>')}</div></div>`).join(''):`<p class="muted">${e(pdfLabel('No source-checked essentials snapshot is saved for this destination and passport. Open Before You Go in TripNexa to check official sources.'))}</p>${base?link(base,pdfLabel('Open trip essentials')):''}`}<div class="footer-note"><h3>${e(pdfLabel("About this information"))}</h3>${e(pdfLabel(essentialsPdfAbout))}</div></section></body></html>`;
}
export const renderTravelBook=async(state,plan,wallet,options)=>withPdfTranslations({state,essentials:options?.essentials},state.ownerId||state.trip.owner_id||state.trip.created_by_id,async()=>renderPdf(await travelBookHtml(state,plan,wallet,options),{allowEmbeddedImages:true}));
