import {BunnySetup} from './IntegrationSetup';
import { useState } from 'react';
import { useAuth } from '@/lib/AuthContext';
import { ActionDialog, PageTitle, LoadState, KeyValues, useAdminData } from './AdminCommon';
import { AdminSettings, ManagedSecrets } from './AdminConfiguration';
export default function AdminStorage() {
  const {user}=useAuth(),{data,error,loading,reload}=useAdminData('/bunny');
  const [testing,setTesting]=useState(false),[result,setResult]=useState(null);
  return <><PageTitle title="Storage & CDN · Bunny" description="Private travel files stay behind account authentication. Public marketing media uses a separate CDN."/><LoadState loading={loading} error={error} retry={reload}/>{data&&<section className="admin-card"><h2>{!data.configured?'Not configured':data.lastTest?.result==='failure'?'Connection error':data.lastTest?.result==='success'?'Connected':'Not tested'}</h2><KeyValues data={{provider:data.provider,storage_zone:data.zone,region:data.region,public_CDN:data.publicCdn,private_access:data.privateAccess,last_successful_test:data.lastSuccessfulTest}}/><KeyValues data={data.stats}/>{user.role==='SUPER_ADMIN'&&<button className="admin-button" onClick={()=>setTesting(true)}>Test Connection</button>}</section>}{result&&<section className="admin-card" role="status"><KeyValues data={result}/></section>}{testing&&<ActionDialog title="Test Bunny connection" target="Bunny Storage" impact="Uploads a tiny temporary object, verifies its contents and deletes it. Existing files are not changed." confirmation="TEST" path="/bunny/test" onClose={()=>setTesting(false)} onDone={value=>{setResult(value);reload();}}/>}<BunnySetup data={data}/><AdminSettings title="Storage provider" only="storage_"/><AdminSettings title="Bunny configuration" only="bunny_"/>{user.role==='SUPER_ADMIN'&&<ManagedSecrets provider="bunny"/>}<section className="admin-card"><h2>Private storage setup</h2><p>Use a dedicated storage zone with no public Pull Zone. Wallet and generated images are served through the authenticated application. The public CDN setting describes marketing assets only; it never exposes private objects.</p><p>Existing local files remain readable after switching provider. Test Bunny before selecting it. Keep the same zone while it contains files.</p></section></>;
}
