import {useState} from 'react';
import {useAuth} from '@/lib/AuthContext';
import {ActionDialog,DataTable,KeyValues,LoadState,useAdminData} from './AdminCommon';

export default function AdminFiles(){
 const {user}=useAuth(),storage=useAdminData('/storage'),grants=useAdminData('/file-grants');
 const [action,setAction]=useState(null),[fileId,setFileId]=useState('');
 return <>
  <DataTable title="Travel Wallet / Files" description="Search by file ID, owner ID or email. Inventory shows technical metadata; private content requires a separate, time-limited approval." path="/files" columns={['id','owner','mime','size_bytes','wallet_managed','attachment_count','physical_status','created_date'].map(key=>({key}))} sorts={['created','size','mime']} filters={[{key:'mime',label:'File type',options:['application/pdf','image/png','image/jpeg','image/webp','image/gif']},{key:'wallet',label:'Wallet',options:['true','false']}]}/>
  <section className="admin-card"><h2>Storage totals</h2><LoadState loading={storage.loading} error={storage.error} retry={storage.reload}/>{storage.data&&<KeyValues data={storage.data.total}/>}</section>
  <section className="admin-card"><h2>Exceptional file access</h2><p>Enter a file ID from the inventory. A different super administrator must approve the request. Each download is audited.</p><button className="admin-button secondary" onClick={()=>{setFileId('');setAction({kind:'request'});}}>Request access</button><LoadState loading={grants.loading} error={grants.error} retry={grants.reload}/>{grants.data?.items.map(grant=><section className="admin-card" key={grant.id}><KeyValues data={{file_id:grant.file_id,requested_by:grant.requested_by,status:grant.status,reason:grant.reason,expires_at:grant.expires_at}}/><div className="admin-actions">{user.role==='SUPER_ADMIN'&&grant.status==='PENDING'&&grant.requested_by!==user.id&&<button className="admin-button secondary" onClick={()=>setAction({kind:'approve',grant})}>Approve for 15 minutes</button>}{user.role==='SUPER_ADMIN'&&['PENDING','APPROVED'].includes(grant.status)&&<button className="admin-button secondary" onClick={()=>setAction({kind:'revoke',grant})}>Revoke</button>}{grant.status==='APPROVED'&&grant.requested_by===user.id&&<a className="admin-button secondary" href={'/api/admin/file-grants/'+grant.id+'/content'}>Download approved file</a>}</div></section>)}{grants.data&&!grants.data.items.length&&<p>No access requests.</p>}</section>
  {action&&<ActionDialog title={action.kind==='request'?'Request file access':action.kind==='approve'?'Approve file access':'Revoke file access'} target={action.grant?.file_id||'Private file'} impact={action.kind==='approve'?'Allows the requester to download this file for 15 minutes.':action.kind==='revoke'?'Ends access under this grant immediately.':'Creates an audited request. No content is disclosed until a different super administrator approves.'} path={'/file-grants'+(action.grant?'/'+action.grant.id+'/'+action.kind:'')} confirmation={action.kind.toUpperCase()} extra={action.kind==='request'?{file_id:fileId}:{minutes:15}} fields={action.kind==='request'?<label>File ID<input required value={fileId} onChange={event=>setFileId(event.target.value)}/></label>:null} onClose={()=>setAction(null)} onDone={grants.reload}/>}
 </>;
}
