import {useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {useAuth} from '@/lib/AuthContext';
import {adminApi} from '@/api/admin';
import {PageTitle,LoadState,KeyValues,ActionDialog,useAdminData,label} from './AdminCommon';
export function AdminDashboard(){
 const [days,setDays]=useState('7'),{data,error,loading,reload}=useAdminData('/overview?days='+days);const charts=useAdminData('/analytics?days='+days);
 return <><PageTitle title="Dashboard" description="A clear view of accounts, trips and system operations."><select aria-label="Time period" value={days} onChange={e=>setDays(e.target.value)}><option value="1">24 hours</option><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select></PageTitle><LoadState loading={loading} error={error} retry={reload}/>{data&&<><div className="admin-grid">{[['Users',data.users],['Trips',data.trips],['Storage',data.files]].map(([title,values])=><section className="admin-card" key={String(title)}><h2>{String(title)}</h2><KeyValues data={values}/></section>)}</div><div className="admin-card"><h2>Today’s operations</h2><KeyValues data={{PDF_exports:data.pdfToday,failed_email_deliveries:data.failedEmailsToday,...Object.fromEntries(data.providers.map(p=>[p.provider+'_requests',p.requests]))}}/><p className="admin-muted">{data.trackingNote}</p></div><div className="admin-grid"><section className="admin-card"><h2>System health</h2><KeyValues data={{MySQL:data.health.database.status,storage:data.health.storage.status,Chrome:data.health.chrome.status,OpenAI:data.health.providers.openai.configured?'Configured':'Not configured',Google:data.health.providers.google.configured?'Configured':'Not configured',SMTP:data.health.providers.smtp.configured?'Configured':'Not configured'}}/><Link to="/admin/health">View full health checks →</Link></section><section className="admin-card"><h2>Recent issues</h2>{data.errors.length?data.errors.map(event=><p key={event.id}>{event.category} · {event.event} · {event.created_at}</p>):<p>No recorded issues.</p>}<Link to="/admin/logs">Open logs →</Link></section></div></>}{charts.data&&<Charts data={charts.data}/>}</>;
}
function Bars({title,items,name='day',value='count'}){const maximum=Math.max(1,...items.map(item=>Number(item[value])||0));return <section className="admin-card"><h2>{title}</h2>{items.length?items.slice(-30).map((item,i)=><div className="admin-bar-row" key={i}><span>{String(item[name]||'Unknown')}</span><div className="admin-bar"><span style={{width:Math.max(1,(Number(item[value])||0)/maximum*100)+'%'}}/></div><strong>{item[value]}</strong></div>):<p className="admin-muted">No events recorded in this period.</p>}</section>;}
function Charts({data}){return <div className="admin-grid"><Bars title="Registrations by day" items={data.users}/><Bars title="Trips created by day" items={data.trips}/><Bars title="Popular destinations" items={data.destinations} name="destination"/><Bars title="Provider requests" items={data.providers.map(item=>({...item,day:item.day+' · '+item.provider}))}/><Bars title="Itinerary generations" items={data.planning.filter(item=>item.event.startsWith('itinerary_'))}/><Bars title="Provider errors" items={data.providers.map(item=>({...item,day:item.day+' · '+item.provider}))} value="errors"/></div>;}
export function AdminAnalytics(){const [days,setDays]=useState('30'),[from,setFrom]=useState(''),[to,setTo]=useState('');const {data,error,loading,reload}=useAdminData('/analytics?'+new URLSearchParams({days,...(from?{from}:{}),...(to?{to}:{})}));return <><PageTitle title="Analytics" description="Aggregated activity. No private documents or prompts."/><div className="admin-toolbar"><select aria-label="Period" value={days} onChange={e=>setDays(e.target.value)}>{[1,7,30,90].map(d=><option key={d} value={d}>{d===1?'24 hours':d+' days'}</option>)}</select><input aria-label="Start date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label="End date" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><LoadState loading={loading} error={error} retry={reload}/>{data&&<><p className="admin-muted">{data.note}</p><Charts data={data}/></>}</>;}
export function AdminUser(){
 const {id}=useParams(),{user:actor}=useAuth(),{data,error,loading,reload}=useAdminData('/users/'+id),[action,setAction]=useState(''),[role,setRole]=useState('USER');const canManage=actor.role==='SUPER_ADMIN'||data?.user.role==='USER';
 return <><PageTitle title="User details" description="Account support without access to passwords or private documents."/><LoadState loading={loading} error={error} retry={reload}/>{data&&<><section className="admin-card"><h2>{data.user.display_name||data.user.email}</h2><KeyValues data={data.user}/><div className="admin-actions">{canManage&&['suspend','reactivate','revoke-sessions','password-reset'].map(item=><button className="admin-button secondary" key={item} onClick={()=>setAction(item)}>{label(item.replaceAll('-',' '))}</button>)}{actor.role==='SUPER_ADMIN'&&<><button className="admin-button secondary" onClick={()=>setAction('role')}>Change role</button><button className="admin-button secondary" onClick={()=>setAction('disable')}>Disable account</button></>}</div></section><section className="admin-card"><h2>Active sessions</h2>{data.sessions.map(session=><div className="admin-record" key={session.id}><KeyValues data={session}/>{canManage&&<button className="admin-button secondary" onClick={()=>setAction('revoke-session:'+session.id)}>Revoke session</button>}</div>)}{!data.sessions.length&&<p>No active sessions.</p>}</section><div className="admin-grid"><section className="admin-card"><h2>Recent trips</h2>{data.trips.map(trip=><p key={trip.id}><Link to={'/admin/trips/'+trip.id}>{trip.name}</Link> · {trip.destination}</p>)}</section><section className="admin-card"><h2>Recent audited actions</h2>{data.activity.map((event,i)=><p key={i}>{event.action} · {event.result} · {event.created_at}</p>)}</section></div>{action&&<ActionDialog title={label(action.split(':')[0].replaceAll('-',' '))} target={data.user.email} impact="The action is audited. Account state or privileges may invalidate sessions." path={'/users/'+id+'/'+action.split(':')[0]} confirmation={action.split(':')[0].toUpperCase()} extra={{role,session_id:action.split(':')[1]}} fields={action==='role'?<label>New role<select value={role} onChange={e=>setRole(e.target.value)}>{['USER','ADMIN','SUPER_ADMIN'].map(r=><option key={r}>{r}</option>)}</select></label>:null} onClose={()=>setAction('')} onDone={reload}/>}</>}</>;
}
export function AdminTrip(){
 const {id}=useParams(),{user}=useAuth(),{data,error,loading,reload}=useAdminData('/trips/'+id),[action,setAction]=useState(''),[preview,setPreview]=useState(null),[publicView,setPublicView]=useState(null),[viewError,setViewError]=useState('');
 return <><PageTitle title="Trip diagnostics" description="Summaries and controlled repair. Travel Wallet contents remain private."/><LoadState loading={loading} error={error} retry={reload}/>{viewError&&<p role="alert">{viewError}</p>}{data&&<><div className="admin-grid"><section className="admin-card"><h2>Summary</h2><KeyValues data={data.trip}/></section><section className="admin-card"><h2>Diagnostics</h2><KeyValues data={data.diagnostics}/><h2>Records</h2><KeyValues data={data.counts}/></section></div><div className="admin-actions"><button className="admin-button secondary" onClick={async()=>{try{setPublicView(await adminApi('/trips/'+id+'/public-view'));}catch(e){setViewError(e.message);}}}>Open public-style view</button><button className="admin-button secondary" onClick={()=>setAction('repair-preview')}>Preview repair</button>{user.role==='SUPER_ADMIN'&&<button className="admin-button secondary" onClick={()=>setAction('delete')}>Delete trip</button>}</div>{publicView&&<section className="admin-card"><h2>Public-style itinerary</h2>{publicView.items.map(item=><p key={item.id}>{item.date} · {item.start_time} · {item.title}</p>)}</section>}{preview&&<section className="admin-card"><h2>Repair preview</h2><KeyValues data={preview.summary}/><p>{preview.note}</p>{preview.preview.items.map((item,i)=><p key={i}>{item.date} · {item.start_time} · {item.title}</p>)}{user.role==='SUPER_ADMIN'&&<button className="admin-button" onClick={()=>setAction('repair-apply')}>Apply this repair</button>}</section>}{action&&<ActionDialog title={label(action.replaceAll('-',' '))} target={data.trip.name} impact={action==='delete'?'Deletes the trip and associated data.':action==='repair-apply'?'Replaces the itinerary using the reviewed preview.':'Calculates a preview. Saved data stays unchanged.'} path={'/trips/'+id+'/'+action} confirmation={action==='repair-preview'?'PREVIEW':action==='repair-apply'?'APPLY':'DELETE'} extra={{token:preview?.token}} onClose={()=>setAction('')} onDone={result=>{if(action==='repair-preview')setPreview(result);else{setPreview(null);reload();}}}/>}</>}</>;
}
export function AdminHealth({provider=false,security=false}){const {data,error,loading,reload}=useAdminData(security?'/security':provider?'/providers/status':'/health');return <><PageTitle title={security?'Security readiness':provider?'AI & Providers':'System health'} description="Configuration is distinct from a successful live check."><button className="admin-button secondary" onClick={reload}>Refresh status</button></PageTitle><LoadState loading={loading} error={error} retry={reload}/>{data&&<div className="admin-grid">{Object.entries(security?data.health:data).map(([key,value])=><section className="admin-card" key={key}><h2>{label(key)}</h2>{typeof value==='object'?<KeyValues data={value}/>:<p>{String(value)}</p>}</section>)}{security&&<section className="admin-card"><h2>Privileged accounts</h2>{data.privileged.map(account=><div className="admin-record" key={account.id}><Link to={'/admin/users/'+account.id}>{account.email}</Link><p>{account.role} · {account.status} · MFA {account.mfa_enabled?'enabled':'not enrolled'}</p></div>)}</section>}</div>}</>;}
