import {useEffect,useState} from 'react';
import {adminApi} from '@/api/admin';
export default function AdminPublicItineraries(){
 const [data,setData]=useState(null),[page,setPage]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState('');
 async function load(){try{setData(await adminApi('/public-itineraries?page='+page));setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[page]);
 async function act(id,action){const reason=window.prompt('Reason for this publication action (no private information):');if(!reason)return;const confirmation=window.prompt('Type UPDATE to confirm.');if(confirmation!=='UPDATE')return;setBusy(id);try{await adminApi('/public-itineraries/'+id,'POST',{action,reason,confirmation});await load();}catch(e){setError(e.message);}finally{setBusy('');}}
 return <section className="admin-card"><p className="admin-caption">DISCOVERY & SEO</p><h1>Public itineraries</h1><p>Only reviewed public snapshots appear here. Source trips and private travel details are not included. Existing accounts require source approval in addition to the traveler’s sharing choice.</p>{error&&<p role="alert">{error}</p>}{!data&&!error?<p role="status">Loading public itineraries…</p>:data&&<><div className="admin-table-wrap"><table><thead><tr>{['Itinerary','Publication','Quality / source','Created / updated','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.items.map(row=><tr key={row.public_id}><td><strong>{row.title}</strong><br/>{row.city} · {row.duration||'—'} days<br/><small>{row.source_kind}</small></td><td>{row.status}<br/>{row.indexable?'Indexable':'Noindex'}<br/><small>{row.reason.replaceAll('_',' ')}</small></td><td>{row.quality_score}/100<br/>{row.source_eligible?'Source approved':'Source needs review'}</td><td><small>Created {row.created_at}<br/>Updated {row.updated_at}</small></td><td><div className="flex flex-wrap gap-2">{row.url&&<a href={row.url} target="_blank" rel="noreferrer">View public page ↗</a>}{[['hide','Unpublish'],['noindex','Force noindex'],['regenerate','Refresh snapshot & SEO'],['restore','Restore after checks'],...(!row.source_eligible?[['allow-source','Approve source account']]:[])].map(([action,label])=><button className="admin-button secondary" key={action} disabled={busy===row.public_id} onClick={()=>act(row.public_id,action)}>{label}</button>)}</div></td></tr>)}</tbody></table></div><div className="flex gap-4 items-center mt-5"><button className="admin-button secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} · {data.total} snapshots</span><button className="admin-button secondary" disabled={page*25>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}</section>;
}
