import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {adminApi} from '@/api/admin';
import {useAuth} from '@/lib/AuthContext';
import {PageTitle} from './AdminCommon';
import DestinationAutocomplete from '@/components/home/DestinationAutocomplete';
const names={getyourguide:'GetYourGuide',viator:'Viator',tiqets:'Tiqets',klook:'Klook'};
const empty={provider:'getyourguide',google_place_id:'',canonical_place_name:'',city:'',country:'',provider_product_id:'',provider_destination_id:'',affiliate_url:'',enabled:true,priority:0,version:0};
export default function AdminAffiliates({initial='providers'}){
 const {user}=useAuth(),superAdmin=user.role==='SUPER_ADMIN';
 const [placeSearch,setPlaceSearch]=useState('');
 const [tab,setTab]=useState(initial),[data,setData]=useState(null),[mappings,setMappings]=useState([]),[stats,setStats]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState(null),[mapping,setMapping]=useState(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[query,setQuery]=useState(''),[page,setPage]=useState(1),[preview,setPreview]=useState(null),[override,setOverride]=useState(null);
 async function load(){try{const [p,m,s]=await Promise.all([adminApi('/affiliates/providers'),adminApi('/affiliates/mappings?q='+encodeURIComponent(query)+'&page='+page),adminApi('/affiliates/analytics')]);setData(p.providers);setMappings(m.items);setStats(s);setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[page]);
 useEffect(()=>{setTab(initial);},[initial]);
 const action=async(fn)=>{setBusy(true);setError('');setNotice('');try{await fn();await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const setConfig=(key,value)=>setEdit(p=>({...p,config:{...p.config,[key]:value}}));
 const setMap=(key,value)=>setMapping(p=>({...p,[key]:value}));
 return <><PageTitle title="Tours & Tickets" description="Official affiliate links. Purchases happen on the partner website; clicks are not bookings."/>
  <div className="admin-toolbar">{[['providers','Providers'],['mappings','Place mappings'],['analytics','Affiliate analytics']].map(([id,label])=><button key={id} className="admin-button secondary" aria-pressed={tab===id} onClick={()=>{setTab(id);setEdit(null);setMapping(null);}}>{label}</button>)}<Link to="/admin/settings">Disclosure & public sharing settings</Link></div>
  {error&&<p role="alert" className="admin-error">{error}</p>}{notice&&<p role="status" className="admin-card">{notice}</p>}{!data&&!error&&<p role="status">Loading providers…</p>}
  {tab==='providers'&&data&&<div className="admin-grid">{data.map(p=><section className="admin-card" key={p.id}><h2>{p.config.display_name}</h2><p>{p.status}</p><p>Priority: {p.config.order} · Clicks today: {p.clicks_today}</p><p>Enabled exact mappings: {p.mappings}</p><p>API: {p.api_status}{p.credential_configured?' · credential stored, connector not activated':''}</p><p className="admin-muted">{p.id==='tiqets'?'Booking API: not required. ':''}{p.id==='klook'?'Advanced API/data feed requires separately granted access.':'Content API is optional; link-only integration works without it.'}</p><p>Last check: {p.checked_at||'Not tested'}</p>{p.last_check&&<p>{p.last_check.ok?'✓':'○'} {p.last_check.note}</p>}<ul className="my-3 text-sm space-y-1"><li>{p.config.partner_id?'✓':'○'} Affiliate account identifier</li><li>{p.config.search_template||p.mappings?'✓':'○'} Official link or exact mapping</li><li>✓ Restricted official domains</li><li>○ API optional</li></ul><a href={p.portal} target="_blank" rel="noopener noreferrer">How to configure: official partner portal ↗</a><div className="admin-actions">{superAdmin&&<button className="admin-button" onClick={()=>{setEdit(p);setReason('');setConfirmed(false);}}>Configure {p.name}</button>}<button disabled={busy} className="admin-button secondary" onClick={()=>action(async()=>{const r=await adminApi('/affiliates/providers/'+p.id+'/test','POST',{reason:'Operator requested local link validation',confirmation:'TEST'});setNotice(r.note);})}>Test integration</button></div></section>)}</div>}
  {edit&&tab==='providers'&&<form className="admin-card mt-5 space-y-4" onSubmit={e=>{e.preventDefault();action(async()=>{await adminApi('/affiliates/providers/'+edit.id,'PUT',{config:edit.config,version:edit.version,reason,confirmation:'SAVE',official_link_confirmed:confirmed});setEdit(null);setNotice('Provider configuration saved.');});}}><h2>Configure {edit.name}</h2>
   <label>Enabled<select value={String(edit.config.enabled)} onChange={e=>setConfig('enabled',e.target.value==='true')}><option value="false">Disabled</option><option value="true">Enabled</option></select></label>
   {[['display_name','Display name'],['partner_id','Partner / account / sitebrand identifier (reference only)'],['language','Default language'],['currency','Default currency']].map(([key,label])=><label key={key}>{label}<input value={edit.config[key]} onChange={e=>setConfig(key,e.target.value)}/></label>)}
   <label>Display order<input type="number" min="1" max="99" value={edit.config.order} onChange={e=>setConfig('order',Number(e.target.value))}/></label>
   <label>Official search URL template<textarea value={edit.config.search_template} onChange={e=>setConfig('search_template',e.target.value)}/></label><p className="admin-muted">Optional. Only use a search format approved by the provider, replacing its search text with {'{query}'}. Partner tracking and campaign parameters stay exactly as pasted. For signed or opaque links, use an exact place mapping without substitutions. No generic homepage fallback.</p>
   <label>Allowed official domains (one per line)<textarea value={edit.config.allowed_hosts.join('\n')} onChange={e=>setConfig('allowed_hosts',e.target.value.split('\n').map(s=>s.trim()).filter(Boolean))}/></label>
   <label>Fallback<select value={edit.config.fallback} onChange={e=>setConfig('fallback',e.target.value)}><option value="search">Approved search template, if configured</option><option value="none">Exact mappings only</option></select></label>
   <label>Future content cache TTL (seconds)<input type="number" min="60" max="86400" value={edit.config.cache_ttl} onChange={e=>setConfig('cache_ttl',Number(e.target.value))}/></label><p className="admin-muted">Link generation does not cache prices or availability. API catalogue search and mapping assistant are unavailable until an approved content connector is activated.</p>
   {edit.secret&&<p><Link to="/admin/ai">Manage write-only {edit.name} API credential</Link> · Storing a credential alone does not connect an API.</p>}
   <label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> This link format came from the official partner portal; I have checked tracking and relevance.</label><label>Reason<input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="admin-actions"><button disabled={busy} className="admin-button">Save configuration</button><button type="button" className="admin-button secondary" onClick={()=>setEdit(null)}>Cancel</button></div>
  </form>}
  {tab==='mappings'&&<><div className="admin-toolbar"><input aria-label="Search attraction or Google place ID" placeholder="Search attraction or Google place ID" value={query} onChange={e=>setQuery(e.target.value)}/><button className="admin-button secondary" onClick={()=>{setPage(1);load();}}>Search</button><button className="admin-button" onClick={()=>{setMapping({...empty});setReason('');setConfirmed(false);setOverride(null);}}>Add exact mapping</button></div>
   <div className="admin-table-wrap"><table><thead><tr><th>Attraction</th><th>Provider</th><th>City</th><th>Enabled</th><th>Actions</th></tr></thead><tbody>{mappings.map(m=><tr key={m.id}><td>{m.canonical_place_name}</td><td>{names[m.provider]}</td><td>{m.city}</td><td>{m.enabled?'Yes':'No'}</td><td><button onClick={()=>{setMapping({...m,enabled:!!m.enabled});setReason('');setConfirmed(false);setOverride(null);}}>Edit</button> · <button disabled={busy} onClick={()=>action(async()=>{setPreview(await adminApi('/affiliates/mappings/'+m.id+'/test','POST',{reason:'Operator requested exact mapping validation',confirmation:'TEST'}));})}>Test mapping</button></td></tr>)}</tbody></table></div><div className="admin-pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button disabled={mappings.length<50} onClick={()=>setPage(p=>p+1)}>Next</button></div>
   {preview&&<p className="admin-card">{preview.note} <a href={preview.url} target="_blank" rel="sponsored noopener noreferrer">Preview destination ↗</a></p>}
   {mapping&&<form className="admin-card space-y-4 mt-4" onSubmit={e=>{e.preventDefault();action(async()=>{await adminApi('/affiliates/mappings','POST',{mapping,reason,confirmation:'SAVE',official_link_confirmed:confirmed});setMapping(null);setNotice('Exact mapping saved.');});}}><h2>Exact global place mapping</h2><label>Provider<select value={mapping.provider} onChange={e=>setMap('provider',e.target.value)}>{Object.entries(names).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
    <DestinationAutocomplete id="affiliate-place-search" purpose="place" label="Find an attraction with Google Maps" value={placeSearch} onChange={setPlaceSearch} onSelect={place=>{setMapping(m=>({...m,google_place_id:place.place_id,canonical_place_name:place.name,city:place.city||'',country:place.country||''}));setPlaceSearch('');setOverride(null);}}/>
    {[['google_place_id','Google place ID'],['canonical_place_name','Canonical attraction name'],['city','City'],['country','Country'],['provider_product_id','Provider product ID (optional)'],['provider_destination_id','Provider attraction / destination ID (optional)'],['affiliate_url','Exact official affiliate URL']].map(([key,label])=><label key={key}>{label}<input required={!key.startsWith('provider_')} value={mapping[key]||''} onChange={e=>{setMap(key,e.target.value);if(key==='google_place_id')setOverride(null);}}/></label>)}
    <label>Priority<input type="number" min="-1000" max="1000" value={mapping.priority} onChange={e=>setMap('priority',Number(e.target.value))}/></label><label>Enabled<select value={String(mapping.enabled)} onChange={e=>setMap('enabled',e.target.value==='true')}><option value="true">Enabled</option><option value="false">Disabled</option></select></label>
    <label><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Official provider-generated affiliate link, matching this exact attraction.</label><label>Reason<input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="admin-actions"><button disabled={busy} className="admin-button">Save mapping</button><button type="button" className="admin-button secondary" onClick={()=>setMapping(null)}>Cancel</button></div>
    <hr/><button type="button" disabled={!mapping.google_place_id||busy} onClick={()=>action(async()=>setOverride(await adminApi('/affiliates/overrides/'+encodeURIComponent(mapping.google_place_id))))}>Load ticket visibility override</button>{override&&<div><label>Ticket options for this exact Google place<select value={override.mode} onChange={e=>setOverride({...override,mode:e.target.value})}>{['AUTO','ALWAYS','NEVER'].map(m=><option key={m}>{m}</option>)}</select></label><button type="button" disabled={busy||reason.length<5} onClick={()=>action(async()=>{await adminApi('/affiliates/overrides/'+encodeURIComponent(mapping.google_place_id),'PUT',{...override,reason,confirmation:'SAVE'});setOverride(null);setNotice('Ticket visibility saved.');})}>Save visibility override</button></div>}
   </form>}
  </>}
  {tab==='analytics'&&stats&&<><div className="admin-card"><h2>Outbound clicks: {stats.totals.clicks}</h2><p>Today: {stats.totals.today} · Unique trips: {stats.totals.unique_trips}</p><p>Sales: N/A · Revenue: N/A · Conversion: N/A</p><p className="admin-muted">{stats.note}</p></div><div className="admin-grid mt-4">{Object.entries(stats.groups).map(([key,rows])=><section className="admin-card" key={key}><h2>Clicks by {key.replaceAll('_',' ')}</h2>{Array.isArray(rows)&&rows.map(r=><p key={r.label}>{r.label||'Unknown'}: {r.clicks}</p>)}</section>)}</div></>}
 </>;
}
