import {useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {adminApi} from '@/api/admin';
export function useAdminData(path){const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);useEffect(()=>{let active=true;setLoading(true);setError('');adminApi(path).then(value=>{if(active)setData(value);}).catch(failure=>{if(active)setError(failure.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[path,version]);return{data,error,loading,reload:()=>setVersion(v=>v+1)};}
export const label=value=>value.replaceAll('_',' ').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,c=>c.toUpperCase());
export function PageTitle({title,description='',children=null}){return <header className="admin-page-title"><div><p className="admin-eyebrow">TripSync operations</p><h1>{title}</h1>{description&&<p>{description}</p>}</div>{children}</header>;}
export function LoadState({loading,error,retry}){return loading?<p role="status" className="admin-card">Loading…</p>:error?<div role="alert">{error} <button className="admin-button secondary" onClick={retry}>Retry</button></div>:null;}
export function KeyValues({data}){return <dl className="admin-values">{Object.entries(data||{}).map(([key,value])=><div key={key}><dt>{label(key)}</dt><dd>{value===null||value===undefined?'Not available':typeof value==='boolean'?value?'Yes':'No':typeof value==='object'?JSON.stringify(value):String(value)}</dd></div>)}</dl>;}
export function DataTable({path,columns,filters=[],sorts=['created'],detailBase='',title,description=''}){
 const [params,setParams]=useSearchParams(),[search,setSearch]=useState(params.get('q')||'');const savedSize=localStorage.getItem('tripsync_admin_page_size')||'25';
 const query=new URLSearchParams(params);if(!query.has('pageSize'))query.set('pageSize',savedSize);
 const {data,error,loading,reload}=useAdminData(path+'?'+query);const update=(key,value)=>{const next=new URLSearchParams(params);next.set(key,value);if(key!=='page')next.set('page','1');setParams(next);};
 return <><PageTitle title={title} description={description}/><form className="admin-toolbar" onSubmit={event=>{event.preventDefault();update('q',search);}}><input aria-label="Search" placeholder="Search…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="admin-button secondary">Search</button>{filters.map(filter=><select key={filter.key} aria-label={filter.label} value={params.get(filter.key)||''} onChange={e=>update(filter.key,e.target.value)}><option value="">{filter.label}: all</option>{filter.options.map(option=><option key={option} value={option}>{label(option)}</option>)}</select>)}<select aria-label="Sort" value={params.get('sort')||sorts[0]} onChange={e=>update('sort',e.target.value)}>{sorts.map(sort=><option key={sort} value={sort}>{label(sort)}</option>)}</select><select aria-label="Order" value={params.get('direction')||'desc'} onChange={e=>update('direction',e.target.value)}><option value="desc">Newest / Z–A</option><option value="asc">Oldest / A–Z</option></select></form><LoadState loading={loading} error={error} retry={reload}/>{!loading&&!error&&data&&<><div className="admin-table-wrap"><table><thead><tr>{columns.map(column=><th key={column.key}>{column.label||label(column.key)}</th>)}</tr></thead><tbody>{data.items.map(row=><tr key={row.id}>{columns.map((column,index)=><td key={column.key}>{index===0&&detailBase?<Link to={detailBase+'/'+row.id}>{String(row[column.key]??row.id)}</Link>:typeof row[column.key]==='boolean'?row[column.key]?'Yes':'No':typeof row[column.key]==='object'?JSON.stringify(row[column.key]):String(row[column.key]??'—')}</td>)}</tr>)}</tbody></table>{!data.items.length&&<p className="admin-empty">No matching records.</p>}</div><div className="admin-pagination"><span>{data.total} records · Page {data.page}</span><select aria-label="Rows per page" value={query.get('pageSize')} onChange={e=>{localStorage.setItem('tripsync_admin_page_size',e.target.value);update('pageSize',e.target.value);}}>{[10,25,50,100].map(size=><option key={size}>{size}</option>)}</select><button disabled={data.page<=1} onClick={()=>update('page',String(data.page-1))}>Previous</button><button disabled={data.page*data.pageSize>=data.total} onClick={()=>update('page',String(data.page+1))}>Next</button></div></>}</>;
}
export function ActionDialog({title,target,impact,path,confirmation,onClose,onDone,fields=null,extra={}}){
 const [reason,setReason]=useState(''),[confirm,setConfirm]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reauth,setReauth]=useState(false);
 async function submit(event){event.preventDefault();setBusy(true);setError('');try{if(reauth)await adminApi('/mfa/verify','POST',{password,code});const result=await adminApi(path,'POST',{...extra,reason,confirmation:confirm});onDone(result);onClose();}catch(failure){setError(failure.message);if(failure.status===403)setReauth(true);}finally{setBusy(false);}}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="admin-shell admin-dialog"><DialogTitle>{title}</DialogTitle><DialogDescription>{target} · {impact}</DialogDescription><form onSubmit={submit}>{fields}<label>Reason (do not include private information)<textarea required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Type {confirmation} to confirm<input required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>{reauth&&<><p>Recent authentication is required.</p><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Authenticator or recovery code<input autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)}/></label></>}{error&&<p role="alert">{error}</p>}<div className="admin-actions"><button className="admin-button" disabled={busy||confirm!==confirmation}>{busy?'Processing…':'Confirm action'}</button><button type="button" className="admin-button secondary" disabled={busy} onClick={onClose}>Cancel</button></div></form></DialogContent></Dialog>;
}
