import { t, translateText } from "@/i18n/runtime";
import { useLocale } from "@/i18n/react";
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Link2} from 'lucide-react';
import AuthLayout from '@/components/AuthLayout';
import {socialApi} from '@/api/social';
export default function SocialLink(){
  useLocale();const [data,setData]=useState(null),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{socialApi('/auth/link-request').then(setData).catch(e=>setError(e.message));},[]);async function submit(e){e.preventDefault();setBusy(true);setError('');try{const result=await socialApi('/auth/link-request',{password});window.location.assign(result.returnTo);}catch(e){setError(e.message);setBusy(false);}}return <AuthLayout icon={Link2} title={t("ui.confirm.your.existing.account.1db123d")} subtitle={t("ui.connect.this.sign.in.method.securely.ec032ac")}><p className="mb-4">{t("ui.an.account.already.uses.this.email.confirm.its.password.to.connec.1b2f861")}{" "}{data?.provider||t("ui.the.provider.42658b9")}.</p>{data&&<form onSubmit={submit} className="space-y-4"><p>{data.email}</p><label className="block">{t("ui.current.password.72ed2bd")}<input className="w-full border rounded-lg p-3 mt-2 bg-transparent" type="password" autoComplete="current-password" value={password} required onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy} className="w-full rounded-lg bg-primary text-primary-foreground p-3">{busy?t("ui.connecting.72021eb"):t("ui.confirm.and.connect.5cf663e")}</button></form>}{error&&<p role="alert" className="my-3 text-red-500">{translateText(error)}</p>}<p className="mt-4"><Link to="/forgot-password" className="underline">{t("ui.reset.password.e0edfeb")}</Link> · <Link to="/login" className="underline">{t("ui.use.another.sign.in.method.9de9ee3")}</Link></p><p className="mt-3 text-sm">{t("ui.you.can.also.sign.in.first.then.connect.the.provider.from.connect.53891ee")}</p></AuthLayout>;}
