// Signed local provider fixtures. Chrome intercepts Google authorization before any external navigation.
import assert from 'node:assert/strict';
import {randomUUID,generateKeyPairSync} from 'node:crypto';
import {once} from 'node:events';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {openBrowser} from './browser-driver.mjs';
assert(/_test$/.test(process.env.MYSQL_TEST_DATABASE||''),'Use a separate MYSQL_TEST_DATABASE ending in _test.');process.env.MYSQL_DATABASE=process.env.MYSQL_TEST_DATABASE;process.env.NODE_ENV='test';
const {pool}=await import('../server/db.js'),{migrate}=await import('../server/migrate.js'),{createApp}=await import('../server/app.js'),{hashPassword}=await import('../server/security.js');await migrate();
const [priorBaselines]=await pool.query('SELECT * FROM oauth_callback_baselines');await pool.query('DELETE FROM oauth_callback_baselines');
const [priorUrls]=await pool.query('SELECT * FROM application_urls'),[priorProviders]=await pool.query('SELECT * FROM social_providers'),[priorSecrets]=await pool.query("SELECT * FROM managed_secrets WHERE secret_name='GOOGLE_OAUTH_CLIENT_SECRET'");
await pool.query('DELETE FROM application_urls');await pool.query('DELETE FROM social_providers');await pool.query("DELETE FROM managed_secrets WHERE secret_name='GOOGLE_OAUTH_CLIENT_SECRET'");
const output=path.resolve('.local/social-verification');await mkdir(output,{recursive:true});const prefix=randomUUID(),owner=randomUUID(),admin=randomUUID(),password='Browser social password 123!';
for(const [id,role]of [[owner,'USER'],[admin,'SUPER_ADMIN']])await pool.execute('INSERT INTO users(id,email,password_hash,email_verified,role)VALUES(?,?,?,TRUE,?)',[id,prefix+'-'+role+'@social-browser.test',await hashPassword(password),role]);
const server=createApp().listen(0,'127.0.0.1');await once(server,'listening');const origin='http://127.0.0.1:'+server.address().port;process.env.PUBLIC_APP_URL=origin;process.env.PUBLIC_SITE_URL=origin;process.env.GOOGLE_OAUTH_CLIENT_ID='browser-fixture';process.env.GOOGLE_OAUTH_CLIENT_SECRET='browser-fixture-secret';
const keys=await generateKeyPair('RS256'),jwk={...await exportJWK(keys.publicKey),kid:'browser-fixture',alg:'RS256'},codes=new Map(),originalFetch=globalThis.fetch;
globalThis.fetch=async(input,options)=>{const url=String(input);if(url==='https://www.googleapis.com/oauth2/v3/certs')return Response.json({keys:[jwk]});if(url==='https://oauth2.googleapis.com/token'){const entry=codes.get(new URLSearchParams(options.body).get('code'));assert(entry);codes.delete(entry.code);return Response.json({id_token:entry.token});}return originalFetch(input,options);};
let browser,subject='browser-new',email=prefix+'-new@social-browser.test';const report={mode:'Local signed Google fixtures; no real provider login',checks:[],failures:[]};const pass=name=>{report.checks.push(name);console.log('PASS',name);};
try{
 browser=await openBrowser(output);const {command,evaluate,text,input,click,screenshot,wait}=browser;
 browser.onEvent('Fetch.requestPaused',async event=>{const url=new URL(event.request.url),code=randomUUID();const token=await new SignJWT({sub:subject,email,email_verified:true,nonce:url.searchParams.get('nonce')}).setProtectedHeader({alg:'RS256',kid:'browser-fixture'}).setIssuer('https://accounts.google.com').setAudience('browser-fixture').setIssuedAt().setExpirationTime('5m').sign(keys.privateKey);codes.set(code,{code,token});const redirect=new URL(url.searchParams.get('redirect_uri'));redirect.searchParams.set('code',code);redirect.searchParams.set('state',url.searchParams.get('state'));await command('Fetch.fulfillRequest',{requestId:event.requestId,responseCode:302,responseHeaders:[{name:'Location',value:redirect.href}],body:''});});
 await command('Fetch.enable',{patterns:[{urlPattern:'https://accounts.google.com/o/oauth2/v2/auth*',requestStage:'Request'}]});
 const go=async(route,expected)=>{await command('Page.navigate',{url:origin+route});if(expected)await text(expected);};
 const api=async(route,body=undefined,method=body?'POST':'GET')=>{const r=await evaluate(`fetch(${JSON.stringify('/api'+route)},{method:${JSON.stringify(method)},headers:{'Content-Type':'application/json','X-Requested-With':'TripSync'},body:${JSON.stringify(body?JSON.stringify(body):undefined)}}).then(async r=>({status:r.status,data:await r.json()}))`);assert(r.status<400,JSON.stringify(r));return r.data;};
 await browser.viewport(390,844);await go('/login','Continue with Google');assert(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'));assert(await evaluate("!!document.querySelector('a[href=\"/register\"]')"));await screenshot('01-login-mobile');pass('Mobile Google button, account link and no horizontal overflow');
 await click('Continue with Google');await text('Your Trips');const first=await api('/auth/me');assert.equal(first.email,email);pass('Google button → intercepted provider → signed callback → normal Home session');await screenshot('02-home-after-google');
 await api('/auth/logout',{});await go('/login','Continue with Google');await click('Continue with Google');await text('Your Trips');assert.equal((await api('/auth/me')).id,first.id);pass('Repeat Google login reuses the same account');
 await go('/profile','My Account');await click('Security & privacy','[role=tab]');await text('Connected accounts');await text('Disconnect');await screenshot('03-connected-mobile');await click('Disconnect');await text('Add a password or another available sign-in method');pass('Social-only last-method disconnect is blocked in the interface');
 await api('/auth/logout',{});subject='browser-collision';email=prefix+'-USER@social-browser.test';await go('/login','Continue with Google');await click('Continue with Google');await text('Confirm your existing account');await input('input[type=password]',password);await evaluate("document.querySelector('form').requestSubmit()");await text('Your Trips');assert.equal((await api('/auth/me')).id,owner);pass('Existing email requires password before identity linking');
 await api('/auth/logout',{});await go('/login','Welcome back');await input('#email',prefix+'-SUPER_ADMIN@social-browser.test');await input('#password',password);await evaluate("document.querySelector('form').requestSubmit()");await text('Your Trips');await pool.execute('UPDATE sessions SET mfa_verified_at=UTC_TIMESTAMP(3) WHERE user_id=?',[admin]);
 await browser.viewport(1440,1100);await go('/admin/domains','Domains & URLs');await text('Generated URLs');await screenshot('04-admin-domains');assert((await api('/admin/domains')).derived.google===origin+'/api/auth/google/callback');pass('Domains page displays effective sources and derived callback URLs');
 await go('/admin/authentication','Authentication Providers');await text('Google client secret');await screenshot('05-admin-authentication');assert(!await evaluate("document.body.innerText.includes('browser-fixture-secret')"));pass('Provider configuration renders without exposing the configured secret');
 await go('/admin/health','System Health');await screenshot('06-health');pass('System Health renders domain and OAuth status');
 await api('/auth/logout',{});await go('/login?socialError=failed','Social sign-in was cancelled');await screenshot('07-login-error');pass('Friendly callback error with password fallback');
 await pool.execute('INSERT INTO social_providers(provider,config)VALUES(?,?)',['google',JSON.stringify({enabled:false,client_id:'browser-fixture',confirmed_callback:origin+'/api/auth/google/callback'})]);await go('/login','Welcome back');await wait("!document.body.innerText.includes('Continue with Google')");pass('Disabled provider disappears without removing password login');
 process.env.APPLE_SERVICE_ID='com.browser.fixture';process.env.APPLE_TEAM_ID='TEAM123456';process.env.APPLE_KEY_ID='KEY1234567';process.env.APPLE_PRIVATE_KEY=generateKeyPairSync('ec',{namedCurve:'P-256'}).privateKey.export({format:'pem',type:'pkcs8'});
 await pool.execute('INSERT INTO application_urls(id,public_site_url,application_url)VALUES(1,?,?)',['https://site.fixture.example','https://app.fixture.example']);await pool.execute('UPDATE social_providers SET config=? WHERE provider=?',[JSON.stringify({enabled:true,client_id:'browser-fixture',confirmed_callback:'https://app.fixture.example/api/auth/google/callback'}),'google']);
 await browser.viewport(390,844);await go('/login','Continue with Apple');await text('Continue with Google');assert(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'));await screenshot('08-login-both-mobile');pass('Google and Apple official button layout fits mobile with HTTPS provider configuration fixtures');
 assert.deepEqual(browser.exceptions,[]);pass('No uncaught browser exceptions');
}catch(error){report.failures.push(error.message);console.error(error);process.exitCode=1;}
finally{
 await writeFile(path.join(output,'report.json'),JSON.stringify(report,null,2));if(browser)await browser.close();globalThis.fetch=originalFetch;await new Promise(resolve=>server.close(resolve));await pool.query('DELETE FROM oauth_callback_baselines');for(const row of priorBaselines)await pool.query('INSERT INTO oauth_callback_baselines SET ?',row);await pool.query('DELETE FROM oauth_flows');await pool.query('DELETE FROM oauth_pending_links');await pool.query('DELETE FROM application_urls');await pool.query('DELETE FROM social_providers');await pool.query("DELETE FROM managed_secrets WHERE secret_name='GOOGLE_OAUTH_CLIENT_SECRET'");for(const row of priorUrls)await pool.query('INSERT INTO application_urls SET ?',row);for(const row of priorProviders)await pool.query('INSERT INTO social_providers SET ?',{...row,config:typeof row.config==='object'?JSON.stringify(row.config):row.config,last_test:row.last_test?JSON.stringify(row.last_test):null});for(const row of priorSecrets)await pool.query('INSERT INTO managed_secrets SET ?',{...row,encrypted_value:typeof row.encrypted_value==='object'?JSON.stringify(row.encrypted_value):row.encrypted_value});await pool.execute('DELETE FROM users WHERE email LIKE ?',[prefix+'%']);await pool.end();
}
