// Actual built UI and HTTP backend; synthetic users/providers, isolated test DB.
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {once} from 'node:events';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {openBrowser} from './browser-driver.mjs';
assert(/_test$/.test(process.env.MYSQL_TEST_DATABASE||''),'Use a separate MYSQL_TEST_DATABASE ending in _test.');
process.env.MYSQL_DATABASE=process.env.MYSQL_TEST_DATABASE;process.env.NODE_ENV='test';
const {pool}=await import('../server/db.js'),{migrate}=await import('../server/migrate.js'),{config}=await import('../server/config.js'),{createApp}=await import('../server/app.js'),{hashPassword}=await import('../server/security.js');
await migrate();config.googleMapsKey='';config.aiKey='';
const output=path.resolve('.local/billing-verification');await mkdir(output,{recursive:true});
const [prior]=await pool.query("SELECT * FROM app_settings WHERE setting_key LIKE 'billing_%' OR setting_key LIKE 'stripe_%'");
const owner=randomUUID(),admin=randomUUID(),password=randomUUID()+'Strong!',email=owner+'@billing-browser.test';
const report={mode:'Built application, real local HTTP/MySQL, synthetic users; no Stripe payment',checks:[],failures:[]};
const pass=value=>{report.checks.push(value);console.log('PASS '+value);};
async function setting(key,value){await pool.execute('INSERT INTO app_settings(setting_key,value,version)VALUES(?,?,1) ON DUPLICATE KEY UPDATE value=VALUES(value)',[key,JSON.stringify(value)]);}
const server=createApp().listen(0,'127.0.0.1');await once(server,'listening');const origin='http://127.0.0.1:'+server.address().port;process.env.PUBLIC_APP_URL=origin;
let browser;
try{
 await setting('billing_enforcement_enabled',true);await setting('billing_enabled',false);await setting('billing_mode','test');
 for(const [id,role] of [[owner,'USER'],[admin,'SUPER_ADMIN']])await pool.execute('INSERT INTO users(id,email,password_hash,email_verified,role)VALUES(?,?,?,TRUE,?)',[id,id+'@billing-browser.test',await hashPassword(password),role]);
 browser=await openBrowser(output);const {command,evaluate,wait,text,input,click,screenshot}=browser;
 const go=async(route,expected)=>{await command('Page.navigate',{url:origin+route});await text(expected);};
 const api=async(route,body,method=body?'POST':'GET')=>evaluate(`fetch(${JSON.stringify('/api'+route)},{method:${JSON.stringify(method)},headers:{'Content-Type':'application/json','X-Requested-With':'TripSync'},body:${JSON.stringify(body?JSON.stringify(body):undefined)}}).then(async r=>({status:r.status,data:await r.json()}))`);
 const close=async()=>{await command('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});await command('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape'});await wait("!document.querySelector('[role=dialog]')");};
 await browser.viewport(1440);await go('/login','Welcome back');await input('#email',email);await input('#password',password);await evaluate("document.querySelector('form').requestSubmit()");await text('Your Trips');
 const created=await api('/entities/Trip',{name:'Rome · Free plan',destination:'Rome',country:'Italy',adults:1,start_date:'2026-10-15',end_date:'2026-10-16'});assert.equal(created.status,201);const trip=created.data;
 await api('/entities/PlaceSelection',{trip_id:trip.id,name:'Colosseum',place_id:'billing-browser-colosseum',city:'Rome',country:'Italy',category:'tourist_attraction',priority:'mandatory',lat:41.8902,lng:12.4922,address:'Rome',desired_duration_min:60});
 assert.equal((await api('/trips/'+trip.id+'/itinerary',{use_ai:false})).status,200);pass('Free user creates and builds a basic itinerary');
 await go('/pricing','Travel your way.');await text('Trip Pack 20');await screenshot('pricing-desktop');assert(await evaluate("[...document.querySelectorAll('.billing-plan button')].every(b=>b.disabled)"));pass('Five canonical prices and truthful disabled checkout');
 await browser.viewport(390,844);await screenshot('pricing-mobile');assert(await evaluate('document.documentElement.scrollWidth<=innerWidth+2'));pass('Pricing fits mobile');
 await go('/billing','lifetime free trip used');await screenshot('free-billing-mobile');
 await browser.viewport(1440);await go('/trip/'+trip.id+'/itinerary','Download PDF');await click('Download PDF');await wait("!!document.querySelector('[role=dialog]')");await screenshot('pdf-paywall-desktop');assert(await evaluate("document.querySelector('[role=dialog]').innerText.includes('Get more')"));
 for(let i=0;i<8;i++){await command('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await command('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});assert(await evaluate("!!document.activeElement.closest('[role=dialog]')"));}pass('Real PDF button opens paywall; keyboard focus is trapped');
 await browser.viewport(390,844);await click('Trip Packs');await screenshot('trip-packs-paywall-mobile');assert(await evaluate("document.querySelectorAll('[role=dialog] .billing-plan').length===3"));assert(await evaluate("document.querySelector('[role=dialog]').scrollWidth<=document.querySelector('[role=dialog]').clientWidth+2"));await close();pass('Trip Pack selector and Escape dismissal work on mobile');
 // Exercise reusable UI with machine-code errors returned by real endpoints.
 for(const [name,route,body] of [['trip-limit','/entities/Trip',{name:'Second trip',destination:'Paris'}],['repair','/trips/'+trip.id+'/repair/preview',{}],['extraction','/ai/wallet-extraction',{trip_id:trip.id,file_url:'/api/uploads/'+randomUUID()}]]){const r=await api(route,body);assert.equal(r.status,402);await evaluate(`window.dispatchEvent(new CustomEvent('billing-required',{detail:${JSON.stringify(r.data)}}))`);await wait("!!document.querySelector('[role=dialog]')");await screenshot(name+'-paywall-mobile');await close();}pass('Trip limit, Smart Repair and extraction machine codes render their paywalls');
 await pool.execute("INSERT INTO billing_operations(id,user_id,trip_id,operation,mode,status)VALUES(?,?,?,'ai_generations','test','succeeded')",[randomUUID(),owner,trip.id]);const ai=await api('/trips/'+trip.id+'/itinerary',{use_ai:true});assert.equal(ai.data.code,'AI_LIMIT_REACHED');await evaluate(`window.dispatchEvent(new CustomEvent('billing-required',{detail:${JSON.stringify(ai.data)}}))`);await wait("!!document.querySelector('[role=dialog]')");await screenshot('ai-limit-paywall-mobile');await close();
 await go('/trip/'+trip.id+'/wallet','Travel Wallet');await click('Add to Trip');await wait("!!document.querySelector('input[aria-label=\"Upload travel files\"]')");
 const walletFiles=[];for(let i=1;i<=5;i++){const file=path.join(output,'synthetic-'+i+'.pdf');await writeFile(file,'%PDF-1.4\nSynthetic billing test\n%%EOF');walletFiles.push(file);}
 const doc=await command('DOM.getDocument'),inputNode=await command('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'input[aria-label="Upload travel files"]'});await command('DOM.setFileInputFiles',{nodeId:inputNode.nodeId,files:walletFiles});await wait("!!document.querySelector('.billing-dialog')");await text('4 / 4 used');await screenshot('wallet-limit-paywall-mobile');await click('Continue with my current plan');pass('Real Wallet upload UI accepts four files and opens paywall for the fifth');
 await pool.execute("INSERT INTO billing_credit_lots(id,user_id,mode,source,granted,remaining)VALUES(?,?,'test','ADMIN_GRANT',5,5)",[randomUUID(),owner]);
 await go('/trip/'+trip.id+'/itinerary','Download PDF');await click('Download PDF');await text('Use 1 trip credit');await click('Use 1 trip credit (5 available)');await wait("!document.querySelector('[role=dialog]')");assert.equal((await api('/billing/status')).data.credits,4);assert.equal((await api('/billing/trips/'+trip.id)).data.premium,true);pass('Existing free trip unlocks using one durable credit');
 const subscription='sub_browser_'+randomUUID().replaceAll('-','');await pool.execute("INSERT INTO billing_subscriptions(provider_id,mode,user_id,plan_code,status,period_start,period_end,cancel_at_period_end)VALUES(?,'test',?,'PRO_ANNUAL','active',UTC_TIMESTAMP()-INTERVAL 1 DAY,UTC_TIMESTAMP()+INTERVAL 1 YEAR,TRUE)",[subscription,owner]);
 await browser.viewport(1440);await go('/billing','Cancellation scheduled');await screenshot('pro-annual-cancellation');pass('Annual period, 20 trip allowance, credits and end-of-period cancellation display');
 await pool.execute("INSERT INTO billing_period_usage(user_id,mode,subscription_id,period_start,period_end,used)SELECT user_id,mode,provider_id,period_start,period_end,20 FROM billing_subscriptions WHERE provider_id=?",[subscription]);await pool.execute('UPDATE billing_credit_lots SET remaining=0 WHERE user_id=?',[owner]);
 const limit=await api('/entities/Trip',{name:'Twenty first',destination:'Paris'});assert.equal(limit.data.limit,20);await evaluate(`window.dispatchEvent(new CustomEvent('billing-required',{detail:${JSON.stringify(limit.data)}}))`);await text('20 / 20 used');await screenshot('pro-period-limit');await close();await pool.execute('UPDATE billing_credit_lots SET remaining=4 WHERE user_id=?',[owner]);pass('Exhausted Pro period displays 20/20 and offers packs');
 await pool.execute("UPDATE billing_subscriptions SET status='past_due',delinquent_since=UTC_TIMESTAMP()-INTERVAL 4 DAY WHERE provider_id=?",[subscription]);await go('/billing','Please update your payment method');await screenshot('past-due-billing');pass('Delinquent subscription shows payment recovery without hiding saved trips');
 await api('/auth/logout',{});await go('/login','Welcome back');await input('#email',admin+'@billing-browser.test');await input('#password',password);await evaluate("document.querySelector('form').requestSubmit()");await text('Your Trips');await pool.execute('UPDATE sessions SET mfa_verified_at=UTC_TIMESTAMP(3) WHERE user_id=?',[admin]);
 await go('/admin/billing','Billing & monetization');await text('Stripe prices and portal');await screenshot('admin-billing');pass('Billing Admin loads overview, usage, webhook history and configuration');
 assert.equal(browser.exceptions.length,0);pass('No unhandled browser exceptions');
}catch(error){report.failures.push(error.message);console.error(error.message);await browser?.screenshot('failure').catch(()=>{});process.exitCode=1;}
finally{await browser?.close();await new Promise(r=>server.close(r));await pool.query("DELETE FROM app_settings WHERE setting_key LIKE 'billing_%' OR setting_key LIKE 'stripe_%'");for(const row of prior)await pool.query('INSERT INTO app_settings SET ?',{...row,value:typeof row.value==='string'?row.value:JSON.stringify(row.value)});const {cleanupWalletFiles}=await import('../server/file-lifecycle.js');for(const id of [owner,admin]){const [files]=await pool.execute('SELECT id FROM uploads WHERE owner_id=?',[id]);await cleanupWalletFiles(files.map(f=>f.id));await pool.execute('DELETE FROM users WHERE id=?',[id]);await pool.execute('DELETE FROM audit_events WHERE actor_user_id=?',[id]);}await pool.end();await writeFile(path.join(output,'report.json'),JSON.stringify(report,null,2));}
