import { appendPlaceRequest } from '@/lib/dining';
import { itineraryTimeLabel } from '@/lib/itinerary-time-label';
import { useEffect,useState } from 'react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { api } from '@/api/client';

export default function ChangeItineraryDialog({trip,version,onClose,onSaved}) {
  const [request,setRequest]=useState(''),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [unscheduled,setUnscheduled]=useState([]),[listError,setListError]=useState(false);
  useEffect(()=>{let active=true;api.getItinerary(trip.id).then(plan=>{if(active)setUnscheduled(plan.unscheduledSelected||[]);}).catch(()=>{if(active)setListError(true);});return()=>{active=false;};},[trip.id]);
  function append(places){const next=appendPlaceRequest(request,places);if(next.length>4000){setError('The request is full. Shorten it before adding more places.');return;}setRequest(next);setError('');}
  async function generate(){setBusy(true);setError('');try{setPreview(await api.previewItinerary(trip.id,{expected_version:version,request}));}catch(failure){setError(failure.message);}finally{setBusy(false);}}
  async function apply(){setBusy(true);setError('');try{onSaved(await api.applyItinerary(trip.id,preview.token));onClose();}catch(failure){setError(failure.message);}finally{setBusy(false);}}
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="trip-modal max-w-2xl w-[95vw] max-h-[90dvh] overflow-y-auto"><DialogTitle>Change your itinerary</DialogTitle><DialogDescription className="text-white/60">Tell TripSync what you'd like to change. Existing bookings and fixed reservations will be protected.</DialogDescription>
    {!preview?<><label htmlFor="itinerary-change" className="text-sm">Your change request</label><textarea id="itinerary-change" rows={6} maxLength={4000} value={request} onChange={event=>setRequest(event.target.value)} placeholder="Move one activity from Day 2 to Day 3 and leave Day 2 afternoon free." className="w-full rounded-xl border p-3" disabled={busy}/><p className="text-xs text-white/60">This request applies to this edit only. Your saved Special wishes remain unchanged.</p>{listError&&<p className="text-xs text-white/60">The selected places list could not load. You can still describe your request.</p>}{unscheduled.length>0&&<details data-unscheduled-selected className="rounded-xl border border-white/15 p-3"><summary className="cursor-pointer text-sm">Selected places not in your itinerary ({unscheduled.length})</summary><div className="max-h-56 overflow-y-auto space-y-3 mt-3">{unscheduled.map(place=><div key={place.selection_id} className="border-t border-white/10 pt-3"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-medium">{place.name}</p><span className="text-xs text-lime">{place.required?'Must-see':'Preferred'}</span></div><p className="text-xs text-white/60 my-2">{place.reason}</p><button disabled={busy} className="trip-link text-sm" onClick={()=>append([place])}>Add to request</button></div>)}</div><button disabled={busy} className="trip-button secondary mt-3" onClick={()=>append(unscheduled)}>Try to include all</button></details>}</>:<section data-change-preview className="space-y-4"><h3 className="font-semibold">Proposed changes</h3><p className="text-sm text-white/80">{preview.summary}</p>{[...new Set(preview.changes.map(change=>change.date))].sort().map(date=><div key={String(date)} className="rounded-xl border border-white/15 p-3"><h4 className="text-lime font-medium">{String(date)}</h4>{preview.changes.filter(change=>change.date===date).map((change,index)=><div key={index} className="mt-2 text-sm"><p><strong>{change.action}:</strong> {change.name}{change.start_time?` at ${change.start_time}`:""}{change.from_date&&change.from_date!==date?` · from ${change.from_date}`:''}</p><p className="text-white/60">{change.reason}</p></div>)}</div>)}<details><summary className="cursor-pointer text-sm">Preview updated schedule</summary>{preview.items.map((item,index)=><p key={index} className="text-xs text-white/70 mt-2">{item.date} · {itineraryTimeLabel(item)} · {item.title}</p>)}</details></section>}
    {error&&<p role="alert" className="text-amber-200 text-sm">{error}</p>}
    <div className="flex flex-wrap gap-3"><button className="trip-button primary" disabled={busy||(!preview&&!request.trim())} onClick={preview?apply:generate}>{busy?preview?'Applying…':'Preparing preview…':preview?'Apply changes':'Preview changes'}</button>{preview&&<button disabled={busy} className="trip-button secondary" onClick={()=>setPreview(null)}>Revise request</button>}<button disabled={busy} className="trip-button secondary" onClick={onClose}>Cancel</button></div>
  </DialogContent></Dialog>;
}
