import { t, translateText } from "@/i18n/runtime";
import { useLocale } from "@/i18n/react";
import { appendPlaceRequest } from '@/lib/dining';
import { itineraryTimeLabel } from '@/lib/itinerary-time-label';
import { useEffect,useState } from 'react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { api } from '@/api/client';

export default function ChangeItineraryDialog({trip,version,onClose,onSaved}) {
  useLocale();
  const [request,setRequest]=useState(''),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [unscheduled,setUnscheduled]=useState([]),[listError,setListError]=useState(false);
  useEffect(()=>{let active=true;api.getItinerary(trip.id).then(plan=>{if(active)setUnscheduled(plan.unscheduledSelected||[]);}).catch(()=>{if(active)setListError(true);});return()=>{active=false;};},[trip.id]);
  function append(places){const next=appendPlaceRequest(request,places);if(next.length>4000){setError('The request is full. Shorten it before adding more places.');return;}setRequest(next);setError('');}
  async function generate(){setBusy(true);setError('');try{setPreview(await api.previewItinerary(trip.id,{expected_version:version,request}));}catch(failure){setError(failure.message);}finally{setBusy(false);}}
  async function apply(){setBusy(true);setError('');try{onSaved(await api.applyItinerary(trip.id,preview.token));onClose();}catch(failure){setError(failure.message);}finally{setBusy(false);}}
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="trip-modal max-w-2xl w-[95vw] max-h-[90dvh] overflow-y-auto"><DialogTitle>{t("ui.change.your.itinerary.3862d4e")}</DialogTitle><DialogDescription className="text-white/60">{t("ui.tell.tripnexa.what.you.d.like.to.change.existing.bookings.and.fix.2ca04f9")}</DialogDescription>
    {!preview?<><label htmlFor="itinerary-change" className="text-sm">{t("ui.your.change.request.c014472")}</label><textarea id="itinerary-change" rows={6} maxLength={4000} value={request} onChange={event=>setRequest(event.target.value)} placeholder={t("ui.move.one.activity.from.day.2.to.day.3.and.leave.day.2.afternoon.f.7a6e46a")} className="w-full rounded-xl border p-3" disabled={busy}/><p className="text-xs text-white/60">{t("ui.this.request.applies.to.this.edit.only.your.saved.special.wishes.491953b")}</p>{listError&&<p className="text-xs text-white/60">{t("ui.the.selected.places.list.could.not.load.you.can.still.describe.yo.1d65b3f")}</p>}{unscheduled.length>0&&<details data-unscheduled-selected className="rounded-xl border border-white/15 p-3"><summary className="cursor-pointer text-sm">{t("ui.selected.places.not.in.your.itinerary.4ad5a97")}{unscheduled.length})</summary><div className="max-h-56 overflow-y-auto space-y-3 mt-3">{unscheduled.map(place=><div key={place.selection_id} className="border-t border-white/10 pt-3"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-medium">{place.name}</p><span className="text-xs text-lime">{place.required?t("ui.must.see.b480a55"):t("ui.preferred.3c757ae")}</span></div><p className="text-xs text-white/60 my-2">{translateText(place.reason)}</p><button disabled={busy} className="trip-link text-sm" onClick={()=>append([place])}>{t("ui.add.to.request.1bf36d9")}</button></div>)}</div><button disabled={busy} className="trip-button secondary mt-3" onClick={()=>append(unscheduled)}>{t("ui.try.to.include.all.6329b6b")}</button></details>}</>:<section data-change-preview className="space-y-4"><h3 className="font-semibold">{t("ui.proposed.changes.486f49f")}</h3><p className="text-sm text-white/80">{translateText(preview.summary)}</p>{[...new Set(preview.changes.map(change=>change.date))].sort().map(date=><div key={String(date)} className="rounded-xl border border-white/15 p-3"><h4 className="text-lime font-medium">{String(date)}</h4>{preview.changes.filter(change=>change.date===date).map((change,index)=><div key={index} className="mt-2 text-sm"><p><strong>{translateText(change.action)}:</strong> {change.name}{change.start_time?` at ${change.start_time}`:""}{change.from_date&&change.from_date!==date?t("ui.from.value.9c3eb50", {v0: change.from_date}):''}</p><p className="text-white/60">{translateText(change.reason)}</p></div>)}</div>)}<details><summary className="cursor-pointer text-sm">{t("ui.preview.updated.schedule.c8ecc6b")}</summary>{preview.items.map((item,index)=><p key={index} className="text-xs text-white/70 mt-2">{item.date} · {itineraryTimeLabel(item)} · {item.title}</p>)}</details></section>}
    {error&&<p role="alert" className="text-amber-200 text-sm">{translateText(error)}</p>}
    <div className="flex flex-wrap gap-3"><button className="trip-button primary" disabled={busy||(!preview&&!request.trim())} onClick={preview?apply:generate}>{busy?preview?t("ui.applying.3329a9b"):t("ui.preparing.preview.11e66e1"):preview?t("ui.apply.changes.85045cc"):t("ui.preview.changes.330c32c")}</button>{preview&&<button disabled={busy} className="trip-button secondary" onClick={()=>setPreview(null)}>{t("ui.revise.request.9d9d554")}</button>}<button disabled={busy} className="trip-button secondary" onClick={onClose}>{t("ui.cancel.19766ed")}</button></div>
  </DialogContent></Dialog>;
}
