// Reviewed editorial content, never populated from user text or provider responses.
// Extend this registry through code review. Unrecognized destinations/places fail closed.
export const slugify = value => String(value).normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const stop = (name, area, note, minutes = 90) => ({ key: slugify(name), name, area, note, minutes });
const day = (title, note, first, second, meal = 'lunch', transport = 'walk') => ({ title, note, stops: [first, second], meal, transport });
const destination = (city, country, timezone, latitude, longitude, persona, intent, summary, source, days) => ({ key: slugify(city), city, country, timezone, latitude, longitude, persona, intent, summary, source, days });
export const DESTINATIONS = [
  destination('Rome','Italy','Europe/Rome',41.9028,12.4964,'first-time','culture','Ancient landmarks, quieter squares and a day across the river, with two main stops each day. Leave room between visits for lunch and unhurried neighborhood walks.','https://turismoroma.it/en/itineraries/rome-72-hours',[
    day('Ancient Rome','Keep the archaeological sights together and leave the afternoon flexible.',stop('Colosseum','Ancient Rome','Choose your entry slot before arranging the rest of this day.',120),stop('Roman Forum','Ancient Rome','Explore the archaeological paths at your own pace; bring water and sun protection.',150)),
    day('The historic center','This compact route pairs an indoor landmark with an open-air square.',stop('Pantheon','Historic center','Look up at the dome, then leave time to explore the surrounding lanes.'),stop('Piazza Navona','Historic center','A relaxed square stop, with room to pause before continuing on foot.',60)),
    day('Art across the Tiber','Allow a substantial museum visit and a later riverside walk.',stop('Vatican Museums','Vatican area','Select a few collections in advance instead of trying to see everything.',180),stop('Castel Sant’Angelo','Prati','Finish near the river; choose an interior visit or enjoy the exterior.',90),'lunch','transit'),
    day('A slower Rome','A green morning and a neighborhood afternoon give this trip a softer finish.',stop('Villa Borghese','Pinciano','Walk the park paths and take a break before crossing to the next area.',120),stop('Trastevere','Trastevere','Explore the public streets and small squares without a packed checklist.',120),'lunch','transit'),
  ]),
  destination('Paris','France','Europe/Paris',48.8566,2.3522,'family','sightseeing','A family plan with a museum or landmark in the morning and space to play or wander later. Each day has just two anchors, leaving time to adapt to the children’s energy.','https://parisjetaime.com/eng/discover-paris/paris-by-theme/paris-for-families/three-days-in-paris-with-the-family-i138',[
    day('The tower and the park','Keep both stops in the same area and reserve a flexible lunch break.',stop('Eiffel Tower','Champ de Mars','Decide whether to go up or enjoy the tower from ground level.',120),stop('Champ de Mars','Champ de Mars','Use this open-space stop for a slower afternoon rather than another queue.',90)),
    day('Art in small doses','A focused museum visit works better than a race through every gallery.',stop('Louvre Museum','Louvre','Choose a short route through a few collections suited to your family.',150),stop('Tuileries Garden','Tuileries','Move outdoors after the museum and leave the rest of the afternoon open.',90)),
    day('Science and gardens','Stay around the Jardin des Plantes, with breaks between the main visits.',stop('Grande Galerie de l’Évolution','Jardin des Plantes','Explore the displays at a pace that leaves time for questions and breaks.',120),stop('Jardin des Plantes','Jardin des Plantes','Follow the garden paths and finish when the family is ready.',90)),
    day('The Left Bank','A garden morning and nearby historic streets make an adaptable final day.',stop('Luxembourg Gardens','Luxembourg','Plan a relaxed garden visit; check any optional activities separately.',120),stop('Latin Quarter','Latin Quarter','Explore a few public streets and choose a nearby place to eat.',90)),
  ]),
  destination('Barcelona','Spain','Europe/Madrid',41.3874,2.1686,'couples','culture','Five days balance architecture, old-town streets, the hillside and the waterfront. Visits are grouped by area, with a slower outdoor stop after the larger sights.','https://www.barcelonaturisme.com/wv3/en/page/5677/itineraries-routes.html',[
    day('The old city','Walk between these neighboring historic areas instead of crossing the city.',stop('Barcelona Cathedral','Gothic Quarter','Check visitor access before choosing an interior visit.',90),stop('Gothic Quarter','Gothic Quarter','Explore the lanes and squares beyond the busiest through-routes.',120)),
    day('Modernist Barcelona','Leave a long pause between two substantial architectural visits.',stop('Sagrada Família','Eixample','Arrange an entry time, then allow space around it for arrival and lunch.',150),stop('Hospital de Sant Pau','Sant Pau','Continue to the nearby modernist site for a separate, unhurried visit.',120)),
    day('The hillside and Gràcia','Use transit for the hillside approach and walk once in the neighborhood.',stop('Park Güell','Gràcia','Plan for hills and check the entrance arrangement before setting out.',120),stop('Gràcia','Gràcia','Spend the afternoon around local squares and public streets.',90),'lunch','transit'),
    day('Montjuïc','Keep the day on the hillside rather than adding distant attractions.',stop('Museu Nacional d’Art de Catalunya','Montjuïc','Select a section of the collections and allow time for the surrounding views.',150),stop('Montjuïc Gardens','Montjuïc','Choose a manageable garden walk; paths and gradients vary.',120),'lunch','transit'),
    day('El Born to the sea','Finish with art and an open-ended waterfront afternoon.',stop('Picasso Museum','El Born','Book around the museum visit and explore nearby streets afterward.',120),stop('Barceloneta','Waterfront','Walk by the seafront and leave the evening free.',90)),
  ]),
  destination('London','United Kingdom','Europe/London',51.5074,-0.1278,'first-time','sightseeing','A first visit organized around Westminster, the City, Bloomsbury and South Kensington. Take public transport between districts and keep the larger museum visits focused.','https://www.visitlondon.com/things-to-do',[
    day('Westminster and the river','Pair a historic interior with a flexible riverside walk.',stop('Westminster Abbey','Westminster','Check visitor arrangements and give the visit a generous morning slot.',120),stop('South Bank','South Bank','Follow a section of the riverside instead of trying to walk its entire length.',120)),
    day('The historic City','These two landmarks fit together with a lunch break between them.',stop('Tower of London','Tower Hill','Allow a substantial visit and prioritize the areas you most want to see.',180),stop('Tower Bridge','Tower Hill','Choose the bridge walk or an exhibition visit according to your energy.',90)),
    day('Museum and neighborhood','Choose a few galleries, then change pace outside.',stop('British Museum','Bloomsbury','A focused selection makes this large museum easier to enjoy.',180),stop('Covent Garden','Covent Garden','Explore the public piazza and surrounding streets without a fixed evening plan.',90)),
    day('South Kensington','Keep this day in west-central London with an outdoor finish.',stop('Natural History Museum','South Kensington','Allow time for popular galleries and breaks during the visit.',180),stop('Kensington Gardens','Kensington','Take a park walk after the museum; shorten it whenever you need.',90)),
  ]),
  destination('New York City','United States','America/New_York',40.7128,-74.006,'first-time','sightseeing','Five days keep Manhattan and Brooklyn visits in manageable clusters. Large museums and long walks have their own space, so transit and meal breaks do not become an afterthought.','https://www.nyctourism.com/things-to-do/',[
    day('Midtown landmarks','Start with two nearby landmarks and explore the blocks between them.',stop('Grand Central Terminal','Midtown','Look around the public concourse while keeping commuter routes clear.',75),stop('New York Public Library','Midtown','Check the visitor route, then pause in the surrounding Midtown area.',90)),
    day('The park and the Met','Combine a selected park walk with a substantial museum afternoon.',stop('Central Park','Upper East Side','Choose a short section of the park rather than crossing it all.',120),stop('Metropolitan Museum of Art','Upper East Side','Pick a small number of collections and leave time for a break.',180)),
    day('Lower Manhattan','Give the memorial a thoughtful visit and keep the later walk flexible.',stop('9/11 Memorial','Lower Manhattan','Allow quiet time at the outdoor memorial; museum entry is a separate choice.',90),stop('Battery Park','Lower Manhattan','Walk the waterfront and enjoy the harbor views without adding a ferry booking.',90)),
    day('Chelsea and the west side','A food stop and an elevated walk form a slower day.',stop('Chelsea Market','Chelsea','Browse the food stalls and choose your meal on the day.',90),stop('High Line','Chelsea','Walk a manageable section and use the exits that suit your onward plans.',120)),
    day('Brooklyn waterfront','Cross to Brooklyn once, then keep the afternoon near the waterfront.',stop('Brooklyn Bridge','East River','Allow extra time for the crossing and share the pedestrian space carefully.',90),stop('Brooklyn Bridge Park','Brooklyn waterfront','Explore the waterfront paths and leave time to sit with the skyline view.',120)),
  ]),
  destination('Tokyo','Japan','Asia/Tokyo',35.6762,139.6503,'first-time','culture','Five days explore distinct sides of Tokyo without treating the whole city as one walking route. Historic streets, museums, parks and contemporary neighborhoods each get a separate day.','https://www.gotokyo.org/en/see-and-do/index.html',[
    day('Asakusa','Keep the first day around the temple district and the nearby river.',stop('Sensō-ji','Asakusa','Visit respectfully and allow time for the surrounding public streets.',120),stop('Sumida Park','Asakusa','Walk beside the river and take a break after the busier temple area.',90)),
    day('Ueno','The museum and park are a practical pairing for a focused cultural day.',stop('Tokyo National Museum','Ueno','Select a few galleries rather than trying to cover every building.',180),stop('Ueno Park','Ueno','Continue outdoors and keep the rest of the afternoon flexible.',90)),
    day('Meiji and Shibuya','Use transit when helpful and avoid overloading this busier part of the city.',stop('Meiji Jingū','Harajuku','Walk the approach calmly and observe the shrine’s visitor guidance.',120),stop('Shibuya Crossing','Shibuya','Explore the nearby streets, allowing for crowds and frequent breaks.',90),'lunch','transit'),
    day('Shinjuku','Balance a garden visit with the surrounding city neighborhood.',stop('Shinjuku Gyoen','Shinjuku','Choose a garden circuit suited to the weather and your walking pace.',150),stop('Shinjuku','Shinjuku','Explore a few streets and choose an evening meal without a rigid route.',90)),
    day('Central Tokyo','Leave time between the gardens and the shopping streets.',stop('Imperial Palace East Gardens','Marunouchi','Check access for your chosen day before planning the garden visit.',120),stop('Ginza','Ginza','Browse the public streets and architecture, with room for a final food stop.',120),'lunch','transit'),
  ]),
  destination('Kyoto','Japan','Asia/Tokyo',35.0116,135.7681,'couples','culture','Three days follow eastern Kyoto, Arashiyama and the south-central area. Temples and neighborhood walks are paired without adding distant sights to every afternoon.','https://kyoto.travel/en/destinations/',[
    day('Higashiyama','Allow for slopes and crowds, then explore nearby lanes at a gentler pace.',stop('Kiyomizu-dera','Higashiyama','Wear comfortable shoes and leave time for the hillside approach.',120),stop('Gion','Higashiyama','Stay on public streets and respect photography restrictions and residents.',120)),
    day('Arashiyama','Travel to the district once and spend the day nearby.',stop('Tenryū-ji','Arashiyama','Give the temple and garden a focused visit before continuing outdoors.',120),stop('Arashiyama Bamboo Grove','Arashiyama','Keep to the paths and combine the short grove walk with the wider area.',90),'lunch','train'),
    day('Fushimi and the center','Leave a transit gap between the shrine and the central food district.',stop('Fushimi Inari Taisha','Fushimi','Walk only as far uphill as suits you; a full climb is optional.',150),stop('Nishiki Market','Central Kyoto','Browse respectfully and eat where vendors indicate it is appropriate.',120),'lunch','train'),
  ]),
  destination('Dubai','United Arab Emirates','Asia/Dubai',25.2048,55.2708,'first-time','sightseeing','Old Dubai, Downtown, the coastline and a museum day offer different views of the city. Transit gaps and indoor breaks leave room to adapt to the heat.','https://www.visitdubai.com/en/things-to-do/itineraries/a-first-timers-guide-to-dubai',[
    day('Old Dubai','Explore the historic district before spending time beside the creek.',stop('Al Fahidi Historical Neighbourhood','Bur Dubai','Choose a short route through the lanes and pause indoors when needed.',120),stop('Dubai Creek','Old Dubai','Keep the waterside visit flexible and check any boat trip separately.',90)),
    day('Downtown','Stay in one district and avoid adding a long cross-city transfer.',stop('Burj Khalifa','Downtown','Choose whether to book a viewing visit; ground-level views are another option.',120),stop('Dubai Mall','Downtown','Use the indoor setting for lunch and an unhurried afternoon.',150)),
    day('The coast','A waterfront day with room to shorten outdoor sections in hot weather.',stop('Dubai Marina','Dubai Marina','Walk a manageable part of the waterfront and build in shaded breaks.',120),stop('JBR Beach','Jumeirah Beach Residence','Keep this as flexible beach time and follow local safety guidance.',120)),
    day('Museum and park','Make the indoor visit the main anchor and use transit to the next stop.',stop('Museum of the Future','Trade Centre','Check entry arrangements before choosing this day’s starting time.',150),stop('Zabeel Park','Zabeel','A slower outdoor finish, adjusted to the weather and your energy.',90),'lunch','transit'),
  ]),
  destination('Amsterdam','Netherlands','Europe/Amsterdam',52.3676,4.9041,'couples','relaxed','Three days pair a museum with a park, canals with a neighborhood, and a slower eastern district. Leave space for canal-side pauses and avoid stacking several major museums in one day.','https://www.iamsterdam.com/en/explore',[
    day('Museum quarter','Spend the morning inside and the afternoon in the neighboring park.',stop('Rijksmuseum','Museum quarter','Choose the collections you most want to see and allow a mid-visit break.',180),stop('Vondelpark','Oud-Zuid','Follow the park paths at a relaxed pace after lunch.',120)),
    day('Canals and Jordaan','Keep this day walkable and allow plenty of unscheduled time.',stop('Canal Ring','Canal Ring','Explore a few canal streets rather than following a long checklist.',120),stop('Jordaan','Jordaan','Look around the public streets and small shops, respecting residential spaces.',120)),
    day('East of the center','A garden visit and a neighborhood walk provide a calmer final day.',stop('Hortus Botanicus Amsterdam','Plantage','Allow time for the gardens and check any indoor access arrangements.',120),stop('Oosterpark','Oost','Finish with a park walk and a flexible nearby meal.',90)),
  ]),
  destination('Lisbon','Portugal','Europe/Lisbon',38.7223,-9.1393,'couples','relaxed','Lisbon’s hills get a day of their own, followed by Belém and a gentler central route. Short visits, pauses and transit options make the plan easy to slow down.','https://www.visitlisboa.com/en/places/alfama',[
    day('Alfama at walking pace','The slopes are part of the day; take breaks rather than chasing every viewpoint.',stop('Alfama','Alfama','Explore the lanes gradually and use a route suited to your mobility.',120),stop('Miradouro de Santa Luzia','Alfama','Pause at the viewpoint and leave the afternoon open for nearby streets.',60)),
    day('Belém','Travel to Belém once and keep both main visits in the area.',stop('Jerónimos Monastery','Belém','Check visitor arrangements and allow time around your chosen entry.',150),stop('Belém Tower','Belém','Enjoy the riverside setting; confirm interior access separately.',90),'lunch','transit'),
    day('The center and river','A central neighborhood visit and a riverside square make an easy finish.',stop('Chiado','Chiado','Explore the streets and stop for coffee without a rigid schedule.',120),stop('Praça do Comércio','Baixa','Finish near the river and leave time for a final walk.',90)),
  ]),
  destination('Istanbul','Türkiye','Europe/Istanbul',41.0082,28.9784,'first-time','culture','Four days move from Sultanahmet to the bazaars, Galata and the Asian side. Keep mosque visits flexible around worship and give each cross-city journey enough space.','https://istanbul.goturkiye.com/see',[
    day('Sultanahmet','Keep this historic district together and check visitor access before setting times.',stop('Hagia Sophia','Sultanahmet','Follow the current visitor route, dress requirements and worship guidance.',120),stop('Blue Mosque','Sultanahmet','Plan respectfully around prayer and allow time in the surrounding square.',90)),
    day('Palace and park','One substantial cultural visit is enough before a quieter outdoor stop.',stop('Topkapı Palace','Sultanahmet','Choose the sections that interest you and allow a generous visit.',180),stop('Gülhane Park','Sultanahmet','Walk the park paths after lunch and take a slower afternoon.',90)),
    day('Bazaars and the Golden Horn','Build in a transit break instead of treating this as a continuous walk.',stop('Grand Bazaar','Beyazıt','Browse a limited part of the market and leave room for breaks.',120),stop('Galata Tower','Galata','Explore the surrounding streets and confirm tower access separately.',120),'lunch','transit'),
    day('Across to Kadıköy','Check transport on the day and keep the main visits on the Asian side.',stop('Kadıköy Market','Kadıköy','Browse the food streets and choose lunch according to what appeals.',120),stop('Moda','Kadıköy','Finish with a neighborhood and waterfront walk at your own pace.',120)),
  ]),
  destination('Prague','Czechia','Europe/Prague',50.0755,14.4378,'couples','culture','A compact three-day plan links the Old Town, castle district and a slower southern day. The main sights have room around them, with hills and cobbled routes kept in mind.','https://prague.eu/en/',[
    day('Old Town to the river','Walk between the square and bridge, allowing time in the intervening streets.',stop('Old Town Square','Old Town','Explore the public square and choose nearby interiors separately.',90),stop('Charles Bridge','Old Town','Cross at an unhurried pace and leave room for the busy pedestrian route.',90)),
    day('The castle district','Allow a substantial morning visit and a downhill neighborhood afternoon.',stop('Prague Castle','Hradčany','Choose a visitor circuit before arrival and avoid squeezing in every building.',180),stop('Malá Strana','Malá Strana','Explore the public streets at a slower pace after the castle.',120)),
    day('A different river view','Leave transit time between the hilltop area and the later riverside walk.',stop('Vyšehrad','Vyšehrad','Walk the public grounds and choose viewpoints suited to your energy.',120),stop('Náplavka','New Town','Finish along the waterfront; any market or event is an optional extra.',90),'lunch','transit'),
  ]),
  destination('Vienna','Austria','Europe/Vienna',48.2082,16.3738,'couples','culture','Three days combine the historic center, Schönbrunn and a separate art day. Museum and palace visits are deliberately limited so there is time for gardens and cafe breaks.','https://www.wien.info/en/recommendations/vienna-in-three-days',[
    day('The historic center','Keep the first day within the central walking area.',stop('St. Stephen’s Cathedral','Innere Stadt','Choose a manageable visit and check tower or interior access separately.',90),stop('Hofburg','Innere Stadt','Select one part of the complex instead of treating it as a single quick stop.',150)),
    day('Schönbrunn','Give the palace and gardens their own day rather than rushing back across town.',stop('Schönbrunn Palace','Hietzing','Arrange your visitor route in advance and allow time before and after it.',150),stop('Schönbrunn Gardens','Hietzing','Choose a garden walk suited to the weather and your walking pace.',120)),
    day('Art and open space','A major gallery visit is paired with a flexible public courtyard area.',stop('Kunsthistorisches Museum','Museum district','Pick the collections you most want to explore and build in a break.',180),stop('MuseumsQuartier','Museum district','Enjoy the public spaces and decide on any extra exhibition on the day.',90)),
  ]),
  destination('Singapore','Singapore','Asia/Singapore',1.3521,103.8198,'first-time','food','Gardens, heritage neighborhoods and food districts shape this four-day plan. MRT journeys and generous meal breaks keep the schedule adaptable in humid weather.','https://www.visitsingapore.com/travel-tips/travelling-to-singapore/itineraries/4-days-in-singapore/',[
    day('The bay','Keep both visits near Marina Bay and take indoor breaks when needed.',stop('Gardens by the Bay','Marina Bay','Choose your garden route and check separately for ticketed conservatories.',180),stop('Merlion Park','Marina Bay','A flexible waterfront stop, with time for the surrounding promenade.',60)),
    day('Chinatown and food','A heritage morning and a hawker-food afternoon keep this day compact.',stop('Buddha Tooth Relic Temple','Chinatown','Follow visitor and dress guidance when entering this religious site.',90),stop('Chinatown Complex Food Centre','Chinatown','Browse before choosing a meal and allow time for queues.',90)),
    day('Two heritage districts','Use the MRT or a short transfer between these distinct neighborhoods.',stop('Kampong Gelam','Kampong Gelam','Explore public streets and respect worshippers around religious sites.',120),stop('Little India','Little India','Make room for food stops while exploring the busy neighborhood streets.',120),'lunch','metro'),
    day('Gardens and Katong','A green morning and a neighborhood afternoon need a clear transit break.',stop('Singapore Botanic Gardens','Tanglin','Choose a shorter garden route and carry water for the walk.',150),stop('Joo Chiat','Katong','Explore the public streets and food choices at a relaxed pace.',120),'lunch','metro'),
  ]),
  destination('Bangkok','Thailand','Asia/Bangkok',13.7563,100.5018,'first-time','culture','Historic sites, riverside temples and neighborhood food stops unfold over four days. Heat breaks and transport time are built into the pace, with no assumption about current entry hours.','https://www.tourismthailand.org/Destinations/Provinces/Bangkok/219',[
    day('The old city','Allow time for dress checks and breaks between nearby major sites.',stop('Grand Palace','Rattanakosin','Check entry guidance before arrival and keep the visit focused.',150),stop('Wat Pho','Rattanakosin','Continue nearby after lunch and explore respectfully at a slower pace.',120)),
    day('Across the river','Leave a generous transfer gap and verify river transport on the day.',stop('Wat Arun','Thonburi','Take your time around the temple grounds and follow local visitor guidance.',120),stop('Talat Noi','Chinatown riverside','Explore public lanes and riverside streets, respecting homes and working spaces.',120),'lunch','public transport'),
    day('Historic neighborhoods','Keep a midday rest before the later food-area visit.',stop('Wat Saket','Pom Prap','Allow for steps and heat; adjust the climb to your comfort.',90),stop('Yaowarat','Chinatown','Browse the neighborhood and choose food stops according to current opening times.',120),'lunch','transit'),
    day('Art and park time','An indoor visit and a green afternoon offer a calmer final day.',stop('Bangkok Art and Culture Centre','Siam','Check the exhibition program and choose a focused route through the building.',120),stop('Lumphini Park','Pathum Wan','Finish with a manageable park walk when the weather is comfortable.',90),'lunch','metro'),
  ]),
];

export const PERSONAS = {'first-time':'First-time visitors',family:'Family with kids',couples:'Couples',solo:'Solo travelers',friends:'Friends'};
export const INTENTS = {culture:'Culture',food:'Food',relaxed:'Relaxed',sightseeing:'Sightseeing',romantic:'Romantic',family:'Family'};
export const MODES = {walk:'Walking',metro:'Metro',transit:'Public transport',taxi:'Taxi',train:'Train','public transport':'Public transport',car:'Car'};
export const MEALS = {breakfast:'Breakfast break',lunch:'Lunch break',dinner:'Dinner break'};
export const destinationByKey = key => DESTINATIONS.find(d => d.key === key);
export const approvedPlace = (destination, name) => destination.days.flatMap(d => d.stops).find(p => slugify(p.name) === slugify(name));
