import { PERSONAS, INTENTS, MODES } from './catalog.js';
import { parseJson } from './sanitize.js';
import { canonicalFor, routeFor, PUBLIC_ORIGIN } from './service.js';
export const escapeHtml = value => String(value??'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escapeHtml;
const json=value=>JSON.stringify(value).replaceAll('<','\\u003c');
const brand='<a class="brand" href="https://tripnexa.app"><img src="/public-itinerary-assets/logo.svg" alt="TripNexa home" width="172" height="36"></a>';
const button=id=>`<a class="button" href="/customize/${e(id)}">Customize with TripNexa <span aria-hidden="true">↗</span></a>`;
export function publicSchema(row,canonical=canonicalFor(row)) {
  const data=parseJson(row.snapshot);
  return [
    {'@context':'https://schema.org','@type':'WebPage',name:row.title,description:row.description,url:canonical},
    {'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Trip Examples',item:'https://tripnexa.app/trip-examples/'},{'@type':'ListItem',position:2,name:row.h1,item:canonical}]},
    {'@context':'https://schema.org','@type':'TouristTrip',name:row.h1,description:row.introduction,touristType:PERSONAS[row.persona],itinerary:{'@type':'ItemList',itemListElement:data.days.map(day=>({'@type':'ListItem',position:day.number,name:`Day ${day.number}: ${day.heading}`,item:{'@type':'ItemList',itemListElement:day.items.filter(i=>i.kind==='visit').map((item,index)=>({'@type':'ListItem',position:index+1,item:{'@type':'TouristAttraction',name:item.name,address:{'@type':'PostalAddress',addressLocality:row.city,addressCountry:row.country}}}))}}))}},
  ];
}
function shell({title,description,canonical,robots='index, follow',schema=[],content}) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(title)}</title><meta name="description" content="${e(description)}"><meta name="robots" content="${robots}"><link rel="canonical" href="${e(canonical)}"><meta property="og:type" content="website"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="https://tripnexa.app/images/brand/social.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${e(title)}"><meta name="twitter:description" content="${e(description)}"><meta name="twitter:image" content="https://tripnexa.app/images/brand/social.png"><link rel="icon" href="/public-itinerary-assets/icon.svg"><link rel="stylesheet" href="/public-itinerary-assets/public.css"><script type="application/ld+json">${json(schema)}</script></head><body><a class="skip" href="#main">Skip to content</a><header><div class="container nav">${brand}<nav aria-label="Main navigation"><a href="https://tripnexa.app/trip-examples/">Trip Examples</a><a href="/login">Log in</a></nav></div></header><main id="main" tabindex="-1">${content}</main><footer><div class="container">${brand}<p>A little planning. A better journey.</p><nav aria-label="Legal"><a href="https://tripnexa.app/privacy/">Privacy</a><a href="https://tripnexa.app/terms/">Terms</a><a href="https://tripnexa.app/contact/">Contact</a></nav></div></footer></body></html>`;
}
export function itineraryCard(row) {
  return `<article class="related-card"><p class="eyebrow">${e(row.country)} · ${row.duration_days} DAYS</p><h3><a href="${e(routeFor(row))}">${e(row.h1)}</a></h3><p>${e(row.description)}</p><a class="text-link" href="${e(routeFor(row))}">View itinerary <span aria-hidden="true">↗</span></a></article>`;
}
export function renderItinerary(row,related=[],canonical=canonicalFor(row)) {
  const data=parseJson(row.snapshot),hasRelated=related.length>0;
  return shell({title:row.title,description:row.description,canonical,robots:row.indexable?'index, follow':'noindex, follow',schema:publicSchema(row,canonical),content:`
    <section class="hero container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="https://tripnexa.app/trip-examples/">Trip Examples</a><span aria-hidden="true">/</span><span>${e(row.city)}</span></nav>
    <div class="hero-grid"><div><p class="eyebrow">${e(row.country)} · YOUR NEXT CHAPTER</p><h1>${e(row.h1)}</h1><div class="badges"><span>${row.duration_days} days</span><span>${e(PERSONAS[row.persona])}</span><span>${e(INTENTS[row.intent])}</span></div><p class="lead">${e(row.introduction)}</p>${button(row.public_id)}<p class="small">Copy this itinerary and optimize it for your dates, hotel and travel preferences.</p></div><figure class="destination-art"><img src="/public-itinerary-assets/${e(row.city_key)}.svg" width="640" height="420" alt="Illustrated travel motif for ${e(row.city)}"><figcaption>${data.editorial_example?'A TripNexa editorial example':'A privacy-reviewed community route'} · Flexible plans, your own pace.</figcaption></figure></div></section>
    <section class="overview container" aria-label="Itinerary overview"><div><p class="eyebrow">A FEW HIGHLIGHTS</p><ul class="highlights">${data.highlights.map(text=>`<li>${e(text)}</li>`).join('')}</ul></div><nav class="day-jumps" aria-label="Jump to a day">${data.days.map(day=>`<a href="#day-${day.number}">Day ${day.number}</a>`).join('')}</nav></section>
    <div class="container itinerary-layout"><div class="days">${data.days.map(day=>`<section class="day" id="day-${day.number}"><div class="day-heading"><span class="day-number">${String(day.number).padStart(2,'0')}</span><div><p class="eyebrow">DAY ${day.number}</p><h2>${e(day.heading)}</h2><p>${e(day.note)}</p></div></div><ol class="timeline">${day.items.map(item=>`<li class="${item.kind==='meal'?'meal':'visit'}"><div class="time"><time>${e(item.time)}</time><span>${item.duration_min} min</span></div><div class="stop"><p class="stop-kind">${item.kind==='meal'?'ROOM FOR A BREAK':e(item.area)}</p><h3>${e(item.name)}</h3>${item.description?`<p>${e(item.description)}</p>`:'<p>Choose a place that fits your tastes and the route on the day.</p>'}</div></li>`).join('')}</ol><p class="transport">Between stops: ${e(MODES[day.transport]||'Public transport')}. Allow time for transfers and breaks.</p></section>`).join('')}</div><aside class="planning-note"><p class="eyebrow">MAKE IT YOURS</p><h2>The route is a starting point.</h2><p>Times are suggested planning slots, not opening hours or confirmed reservations. Check current access, tickets, transport, weather and accessibility with the provider before traveling.</p><p>These days are sightseeing days. Add your own arrival and departure time when you personalize the plan.</p><a class="text-link" href="${e(data.source_url)}" rel="noopener noreferrer">Official destination guide ↗</a>${button(row.public_id)}</aside></div>
    ${hasRelated?`<section class="container related"><p class="eyebrow">KEEP EXPLORING</p><h2>Another route to inspiration.</h2><div class="related-grid">${related.map(itineraryCard).join('')}</div></section>`:''}
    <section class="closing"><div class="container"><p class="eyebrow">YOUR DATES. YOUR KIND OF TRIP.</p><h2>Turn this plan into your next journey.</h2><p>Add your dates, accommodation and travel details. Then use TripNexa?s planning tools to shape the days.</p>${button(row.public_id)}</div></section>`});
}
export function renderCollection(destination,rows,indexable=false) {
  return shell({title:`${destination.city} itinerary examples | TripNexa`,description:`Explore practical ${destination.city} itinerary examples and customize a day-by-day plan for your trip.`,canonical:`${PUBLIC_ORIGIN}/trips/${destination.key}/`,robots:indexable?'index, follow':'noindex, follow',content:`<section class="container collection"><p class="eyebrow">TRIP EXAMPLES · ${e(destination.country)}</p><h1>${e(destination.city)} itinerary ideas</h1><p class="lead">Find a day-by-day starting point, then make it your own in TripNexa.</p><div class="related-grid">${rows.map(itineraryCard).join('')}</div><a class="text-link" href="https://tripnexa.app/trip-examples/">Explore more destinations ↗</a></section>`});
}
export function renderUnavailable() {
  return shell({title:'Itinerary unavailable | TripNexa',description:'This public itinerary is no longer available. Explore other TripNexa travel examples.',canonical:`${PUBLIC_ORIGIN}/trips/`,robots:'noindex, follow',content:'<section class="container collection"><p class="eyebrow">A CHANGE OF PLANS</p><h1>This itinerary is no longer available.</h1><p class="lead">The traveler may have changed their sharing preferences. There are other routes to explore.</p><a class="button" href="https://tripnexa.app/trip-examples/">Explore Trip Examples ↗</a></section>'});
}
