import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api} from '@/api/client';
export default function TripHealth({tripId,onUpdated}){
 const [health,setHealth]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[preview,setPreview]=useState(null),[review,setReview]=useState(false);
 const load=()=>api.tripHealth(tripId).then(setHealth).catch(e=>setError(e.message));
 useEffect(()=>{let active=true;api.tripHealth(tripId).then(value=>{if(active)setHealth(value);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[tripId]);
 async function run(action){setBusy(action);setError('');try{if(action==='preview'){setPreview(await api.repairTrip(tripId,'preview'));setReview(false);}else{await api.repairTrip(tripId,action,action==='apply'?preview.token:health.undoToken);setPreview(null);await load();onUpdated();}}catch(e){setError(e.message);}finally{setBusy('');}}
 return <section id="trip-health" className="trip-card my-6 scroll-mt-6" aria-busy={!!busy}>
  <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="trip-eyebrow">Trip Health</p><h2 className="text-xl font-semibold mt-2">{health?health.status==='READY'?'Everything looks good':health.status==='UPDATE AVAILABLE'?'An itinerary update is available':`${health.issues.length} things to review`:'Checking your trip…'}</h2></div>{health&&<button className="trip-button secondary" onClick={()=>setReview(true)}>Review readiness</button>}</div>
  {error&&<p role="alert" className="mt-3 text-amber-200">{error} <button className="underline min-h-11" onClick={()=>{setError('');load();}}>Try again</button></p>}
  {health&&<><div className="mt-5"><h3 className="font-semibold">What's next</h3>{health.nextActions.length?<ul className="grid md:grid-cols-3 gap-3 mt-3">{health.nextActions.map(action=><li key={action.title} className="rounded-xl bg-white/5 p-4"><p className="text-sm">{action.title}</p>{action.severity==='update'?<button className="trip-link min-h-11 text-sm" disabled={!!busy} onClick={()=>run('preview')}>{busy==='preview'?'Calculating…':'Preview update'}</button>:<Link className="trip-link min-h-11 inline-flex items-center text-sm" to={action.href}>{action.action}</Link>}</li>)}</ul>:<p className="trip-muted mt-2">Your trip is ready. Enjoy the journey.</p>}</div>
   {health.optionalSaved>0&&<p className="trip-muted mt-4">{health.optionalSaved} optional places are saved for later. They do not affect your trip readiness.</p>}
   <details key={String(health.nearDeparture)} open={health.nearDeparture} className="mt-5 border-t border-white/10 pt-4"><summary className="cursor-pointer font-semibold min-h-11">Before You Go</summary><ul className="grid sm:grid-cols-2 gap-3">{health.beforeGo.map(item=><li key={item.title}><Link to={item.href} className="flex items-center gap-2 text-sm min-h-11"><span aria-hidden>{item.ready?'✓':'○'}</span>{item.title}</Link></li>)}</ul>{!health.beforeGo.length&&<p className="trip-muted">Your travel reminders will appear as you complete your plan.</p>}</details>
   {health.undoToken&&<button className="trip-button secondary mt-3" disabled={!!busy} onClick={()=>run('undo')}>{busy==='undo'?'Restoring…':'Undo last itinerary update'}</button>}
  </>}
  <Dialog open={review||!!preview} onOpenChange={open=>{if(!open&&!busy){setReview(false);setPreview(null);}}}><DialogContent className="bg-neutral-950 text-white border-white/15 max-h-[90dvh] overflow-y-auto"><DialogTitle>{preview?'Review your itinerary update':'Trip readiness'}</DialogTitle><DialogDescription>{preview?'Check the proposed changes before saving. Your current itinerary is safe until you apply.':'A checklist based on your saved trip. Optional details are never required.'}</DialogDescription>
   {preview?<><div className="grid grid-cols-2 gap-3"><p>Current<br/><strong>{preview.before} itinerary items</strong></p><p>Proposed<br/><strong>{preview.after} itinerary items</strong></p></div><h3 className="font-semibold">Changes</h3><ul className="list-disc pl-5 text-sm space-y-2">{preview.changes.map(text=><li key={text}>{text}</li>)}</ul><h3 className="font-semibold">Kept as saved</h3><p className="text-sm text-white/70">{preview.unchanged.join(' · ')}</p>{preview.issues.length>0&&<details><summary>Still to review ({preview.issues.length})</summary><ul className="text-sm mt-2 space-y-2">{preview.issues.map((text,i)=><li key={i}>{text}</li>)}</ul></details>}<button disabled={!!busy} className="trip-button primary" onClick={()=>run('apply')}>{busy==='apply'?'Saving…':'Apply repair'}</button></>:health&&<><ul className="space-y-3">{health.checks.map(check=><li key={check.title} className="flex gap-2 text-sm"><span aria-hidden>{check.ready?'✓':'○'}</span>{check.title}{check.optional&&!check.ready?' — optional':''}</li>)}</ul>{health.canRepair&&<button className="trip-button primary" disabled={!!busy} onClick={()=>run('preview')}>{busy==='preview'?'Calculating…':'Preview repair'}</button>}</>}
   {error&&<p role="alert" className="text-amber-200 text-sm">{error}</p>}<button className="trip-button secondary" disabled={!!busy} onClick={()=>{setReview(false);setPreview(null);}}>Cancel</button>
  </DialogContent></Dialog>
 </section>;
}
