import { t, translateText } from "@/i18n/runtime";
import { useLocale } from "@/i18n/react";
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api} from '@/api/client';
export default function TripHealth({tripId,onUpdated}){
  useLocale();
 const [health,setHealth]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[preview,setPreview]=useState(null),[review,setReview]=useState(false);
 const load=()=>api.tripHealth(tripId).then(setHealth).catch(e=>setError(e.message));
 useEffect(()=>{let active=true;api.tripHealth(tripId).then(value=>{if(active)setHealth(value);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[tripId]);
 async function run(action){setBusy(action);setError('');try{if(action==='preview'){setPreview(await api.repairTrip(tripId,'preview'));setReview(false);}else{await api.repairTrip(tripId,action,action==='apply'?preview.token:health.undoToken);setPreview(null);await load();onUpdated();}}catch(e){setError(e.message);}finally{setBusy('');}}
 return <section id="trip-health" className="trip-card my-6 scroll-mt-6" aria-busy={!!busy}>
  <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="trip-eyebrow">{t("ui.trip.health.cb46584")}</p><h2 className="text-xl font-semibold mt-2">{health?health.status==='READY'?t("ui.everything.looks.good.62ec6b1"):health.status==='UPDATE AVAILABLE'?t("ui.an.itinerary.update.is.available.5e6f548"):t("ui.value.things.to.review.7437f68", {v0: health.issues.length}):t("ui.checking.your.trip.1cb3fb6")}</h2></div>{health&&<button className="trip-button secondary" onClick={()=>setReview(true)}>{t("ui.review.readiness.e482357")}</button>}</div>
  {error&&<p role="alert" className="mt-3 text-amber-200">{translateText(error)} <button className="underline min-h-11" onClick={()=>{setError('');load();}}>{t("ui.try.again.d8b8392")}</button></p>}
  {health&&<><div className="mt-5"><h3 className="font-semibold">{t("ui.what.s.next.eaf380e")}</h3>{health.nextActions.length?<ul className="grid md:grid-cols-3 gap-3 mt-3">{health.nextActions.map(action=><li key={action.title} className="rounded-xl bg-white/5 p-4"><p className="text-sm">{translateText(action.title)}</p>{action.severity==='update'?<button className="trip-link min-h-11 text-sm" disabled={!!busy} onClick={()=>run('preview')}>{busy==='preview'?t("ui.calculating.224798d"):t("ui.preview.update.21541fb")}</button>:<Link className="trip-link min-h-11 inline-flex items-center text-sm" to={action.href}>{translateText(action.action)}</Link>}</li>)}</ul>:<p className="trip-muted mt-2">{t("ui.your.trip.is.ready.enjoy.the.journey.2917ca8")}</p>}</div>
   {health.optionalSaved>0&&<p className="trip-muted mt-4">{health.optionalSaved}{" "}{t("ui.optional.places.are.saved.for.later.they.do.not.affect.your.trip.4279d86")}</p>}
   <details key={String(health.nearDeparture)} open={health.nearDeparture} className="mt-5 border-t border-white/10 pt-4"><summary className="cursor-pointer font-semibold min-h-11">{t("ui.before.you.go.f849009")}</summary><ul className="grid sm:grid-cols-2 gap-3">{health.beforeGo.map(item=><li key={item.title}><Link to={item.href} className="flex items-center gap-2 text-sm min-h-11"><span aria-hidden>{item.ready?'✓':'○'}</span>{translateText(item.title)}</Link></li>)}</ul>{!health.beforeGo.length&&<p className="trip-muted">{t("ui.your.travel.reminders.will.appear.as.you.complete.your.plan.7ea6fec")}</p>}</details>
   {health.undoToken&&<button className="trip-button secondary mt-3" disabled={!!busy} onClick={()=>run('undo')}>{busy==='undo'?t("ui.restoring.5a4918e"):t("ui.undo.last.itinerary.update.8256e2f")}</button>}
  </>}
  <Dialog open={review||!!preview} onOpenChange={open=>{if(!open&&!busy){setReview(false);setPreview(null);}}}><DialogContent className="bg-neutral-950 text-white border-white/15 max-h-[90dvh] overflow-y-auto"><DialogTitle>{preview?t("ui.review.your.itinerary.update.8a60eab"):t("ui.trip.readiness.29f5e57")}</DialogTitle><DialogDescription>{preview?t("ui.check.the.proposed.changes.before.saving.your.current.itinerary.i.370beee"):t("ui.a.checklist.based.on.your.saved.trip.optional.details.are.never.r.0f6d519")}</DialogDescription>
   {preview?<><div className="grid grid-cols-2 gap-3"><p>{t("ui.current.e0d1b68")}<br/><strong>{preview.before}{" "}{t("ui.itinerary.items.c536f7d")}</strong></p><p>{t("ui.proposed.9b0c660")}<br/><strong>{preview.after}{" "}{t("ui.itinerary.items.c536f7d")}</strong></p></div><h3 className="font-semibold">{t("ui.changes.bbd4b6a")}</h3><ul className="list-disc pl-5 text-sm space-y-2">{preview.changes.map(text=><li key={text}>{translateText(text)}</li>)}</ul><h3 className="font-semibold">{t("ui.kept.as.saved.a9fb97e")}</h3><p className="text-sm text-white/70">{preview.unchanged.map(translateText).join(' · ')}</p>{preview.issues.length>0&&<details><summary>{t("ui.still.to.review.67397d0")}{preview.issues.length})</summary><ul className="text-sm mt-2 space-y-2">{preview.issues.map((text,i)=><li key={i}>{translateText(text)}</li>)}</ul></details>}<button disabled={!!busy} className="trip-button primary" onClick={()=>run('apply')}>{busy==='apply'?t("ui.saving.23e3929"):t("ui.apply.repair.4d0ab2d")}</button></>:health&&<><ul className="space-y-3">{health.checks.map(check=><li key={check.title} className="flex gap-2 text-sm"><span aria-hidden>{check.ready?'✓':'○'}</span>{translateText(check.title)}{check.optional&&!check.ready?t("ui.optional.d784a63"):''}</li>)}</ul>{health.canRepair&&<button className="trip-button primary" disabled={!!busy} onClick={()=>run('preview')}>{busy==='preview'?t("ui.calculating.224798d"):t("ui.preview.repair.c0441e0")}</button>}</>}
   {error&&<p role="alert" className="text-amber-200 text-sm">{translateText(error)}</p>}<button className="trip-button secondary" disabled={!!busy} onClick={()=>{setReview(false);setPreview(null);}}>{t("ui.cancel.19766ed")}</button>
  </DialogContent></Dialog>
 </section>;
}
